#!/usr/bin/env python3
# Copyright (c) 2026 The Bitcoin Core developers
# Copyright (c) 2026 defenwycke
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit/.
"""Generate src/test/data/rung_tx_vectors.json — reproducible v4 RUNG_TX
fund+spend reference vectors covering all eight witness-rule families
(Fixed N, Empty, Reveal P, Triplets K, Accumulator, Bridging,
PQ-anchor, Unspendable).

Run:
    python3 test/functional/generate_rung_tx_vectors.py

Each vector is generated by funding an MLSC output via createrungtx
(MiniWallet supplies the input + signs the bootstrap), then spending
the MLSC output via signrungtx where applicable. Key material is
derived deterministically from a seed string (SHA-256(seed)) so re-runs
produce byte-identical vectors.

This is the activation-gate-component-3 generator. The current set is
the seed for expansion toward the 50+ vector bar (positive + negative
+ edge cases per rule family).

The script writes to a temp file then renames over
src/test/data/rung_tx_vectors.json so partially-generated runs can't
corrupt the committed fixture.
"""

import hashlib
import json
import os
import sys
from decimal import Decimal
from pathlib import Path
# `os` import is used by VECTORS_REGENERATE env-var check below.

from test_framework.blocktools import COINBASE_MATURITY
from test_framework.crypto.ripemd160 import ripemd160
from test_framework.key import ECKey
from test_framework.messages import tx_from_hex
from test_framework.test_framework import BitcoinTestFramework, SkipTest
from test_framework.wallet import MiniWallet
from test_framework.wallet_util import bytes_to_wif


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "src" / "test" / "data" / "rung_tx_vectors.json"


def derive_key(seed: str) -> ECKey:
    """Deterministic ECKey from seed string. SHA-256 the seed; tweak the
    last byte if (extremely unlikely) it lands on the curve order or
    zero."""
    h = hashlib.sha256(seed.encode()).digest()
    if h == b"\x00" * 32:
        h = b"\x01" * 32
    k = ECKey()
    k.set(h, True)
    return k


def schnorr_pk_compressed(k: ECKey) -> bytes:
    return k.get_pubkey().get_bytes()


def write_or_verify_vectors(vectors: list, source_description: str):
    """Default behaviour is VERIFY: compare regenerated bytes to the
    committed fixture and fail on drift. With `VECTORS_REGENERATE=1`
    in the environment, overwrite the committed fixture instead.

    This is the CI-load-bearing path: any consensus change that would
    invalidate a vector causes `make check` to fail with a clear diff."""
    payload = {
        "version": 1,
        "description": source_description,
        "vectors": vectors,
    }
    new_text = json.dumps(payload, indent=2) + "\n"
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    if os.environ.get("VECTORS_REGENERATE") == "1":
        tmp = OUTPUT_PATH.with_suffix(".json.tmp")
        tmp.write_text(new_text)
        tmp.replace(OUTPUT_PATH)
        print(f"wrote {len(vectors)} vectors -> {OUTPUT_PATH}")
        return

    # Verify mode (default).
    if not OUTPUT_PATH.exists():
        raise AssertionError(
            f"{OUTPUT_PATH} does not exist; "
            f"run with VECTORS_REGENERATE=1 to create it"
        )
    existing_text = OUTPUT_PATH.read_text()
    if existing_text == new_text:
        print(f"verified {len(vectors)} vectors == {OUTPUT_PATH.name}")
        return

    # Drift — produce a useful diff hint and fail.
    import difflib
    diff_lines = list(difflib.unified_diff(
        existing_text.splitlines(), new_text.splitlines(),
        fromfile=f"committed/{OUTPUT_PATH.name}",
        tofile="regenerated",
        n=2,
        lineterm="",
    ))
    diff = "\n".join(diff_lines[:80])
    raise AssertionError(
        f"FIXTURE DRIFT in {OUTPUT_PATH.name}: regenerated bytes "
        f"differ from committed file. If this is intentional, "
        f"re-run with VECTORS_REGENERATE=1.\n\n{diff}\n"
        f"(diff truncated; first 80 lines)"
    )


# Backward-compat alias — older code paths may still call write_vectors.
write_vectors = write_or_verify_vectors


# ──────────────────────────────────────────────────────────────────
# Vector helpers
# ──────────────────────────────────────────────────────────────────

def _fund_and_capture(node, wallet, rungs: list, label: str):
    """Drive a baseline fund tx via createrungtx + wallet sign;
    return the {fund_tx, mlsc_value_btc, conditions_root, spk}
    bundle."""
    utxo = wallet.get_utxo()
    amt = (Decimal(str(utxo["value"])) - Decimal("0.001")).quantize(Decimal("0.00000001"))
    result = node.createrungtx(
        [{"txid": utxo["txid"], "vout": utxo["vout"]}],
        [amt],
        rungs,
    )
    tx = tx_from_hex(result["hex"])
    wallet.sign_tx(tx)
    signed_hex = tx.serialize().hex()
    txid = node.sendrawtransaction(signed_hex)
    return {
        "fund_txid": txid,
        "fund_hex": signed_hex,
        "fund_size_bytes": len(signed_hex) // 2,
        "mlsc_scriptpubkey": result["scriptPubKey"],
        "mlsc_value_btc": float(amt),
        # `conditions_root` is what's on the wire — for single-SIG-rung
        # txs this is the BIP-341-style tweaked root (key_path=true).
        # `merkle_root` is the untweaked TX_MLSC root, exposed so an
        # independent verifier can validate leaf+tree logic separately
        # from the tweak step (which is just BIP-341 with a "LadderTweak/
        # v1" tag).
        "merkle_root": result.get("merkle_root"),
        "conditions_root": result["conditions_root"],
        "key_path": result.get("key_path", False),
        "internal_pubkey": result.get("internal_pubkey"),
    }


# ──────────────────────────────────────────────────────────────────
# Vector specs — each function returns a vector dict
# ──────────────────────────────────────────────────────────────────
#
# Existing baseline (already in the fixture; re-generated here so the
# whole file is reproducible from this script):
#   1. SIG (Fixed N + key-path tweak)
#   2. P2WPKH_LEGACY (Bridging — HASH160-committed pubkey)
#   3. HTLC (Reveal P + Triplets K — claim path)
#
# New positive coverage:
#   4. CSV (Empty — relative timelock)
#   5. CLTV (Empty — absolute timelock)
#   6. MULTISIG 2-of-3 (Triplets K — proper multisig with inner-Merkle)
#   7. CTV (Empty — covenant template hash)
#   8. PQ_BATCH single-input (PQ-anchor — anchor witness only)
#   9. DATA_RETURN (Unspendable — embed payload, never spend)
#
# Future expansion: ACCUMULATOR (Accumulator), HASH_GUARDED (Reveal-P),
# P2SH_LEGACY (Bridging with inner CSV), VAULT_LOCK (Fixed N w/ 2 keys),
# TIMELOCKED_MULTISIG, ANCHOR_FEE, plus negative vectors for each
# rule family.


def vec_1_sig_keypath(node, wallet) -> dict:
    seed_fund = "bip-xxxx-vec1-fund-key"
    seed_sweep = "bip-xxxx-vec1-sweep-key"
    fund_pk = derive_key(seed_fund)
    sweep_pk = derive_key(seed_sweep)
    fund_pk_hex = schnorr_pk_compressed(fund_pk).hex()
    sweep_pk_hex = schnorr_pk_compressed(sweep_pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "SIG", "fields": [
            {"type": "SCHEME", "hex": "01"},
            {"type": "PUBKEY", "hex": fund_pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec1")
    return {
        "id": 1,
        "name": "SIG single-rung Schnorr key-path",
        "witness_rule": "Fixed N + key-path tweak",
        "block_types": ["SIG"],
        "key_seeds": {"fund": seed_fund, "sweep": seed_sweep},
        "fund_pubkey_compressed": fund_pk_hex,
        "sweep_pubkey_compressed": sweep_pk_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_2_p2wpkh_legacy(node, wallet) -> dict:
    seed_p2wpkh = "bip-xxxx-vec2-p2wpkh-key"
    pk = derive_key(seed_p2wpkh)
    pk_hex = schnorr_pk_compressed(pk).hex()
    # P2WPKH_LEGACY conditions take PUBKEY in the spec; createrungtx
    # computes HASH160 itself.
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "P2WPKH_LEGACY", "fields": [
            {"type": "PUBKEY", "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec2")
    return {
        "id": 2,
        "name": "P2WPKH_LEGACY wrapper (HASH160-committed pubkey)",
        "witness_rule": "Bridging (legacy P2*)",
        "block_types": ["P2WPKH_LEGACY"],
        "key_seeds": {"p2wpkh": seed_p2wpkh},
        "p2wpkh_pubkey_compressed": pk_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_3_htlc(node, wallet) -> dict:
    seed_recv = "bip-xxxx-vec3-htlc-recv"
    seed_send = "bip-xxxx-vec3-htlc-send"
    recv_pk = derive_key(seed_recv)
    send_pk = derive_key(seed_send)
    recv_pk_hex = schnorr_pk_compressed(recv_pk).hex()
    send_pk_hex = schnorr_pk_compressed(send_pk).hex()
    preimage = b"\x42" * 32
    payment_hash = hashlib.sha256(preimage).digest()
    # HTLC conditions: [HASH256, NUMERIC(csv), SCHEME] — createrungtx
    # accepts HASH256 directly here (it's an external commitment, not
    # auto-derived from PREIMAGE for HTLC's claim path).
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "HTLC", "fields": [
            {"type": "PREIMAGE", "hex": preimage.hex()},  # createrungtx will compute HASH256
            {"type": "NUMERIC",  "hex": "90000000"},     # CSV = 144 (LE)
            {"type": "SCHEME",   "hex": "01"},
            {"type": "PUBKEY",   "hex": recv_pk_hex},
            {"type": "PUBKEY",   "hex": send_pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec3")
    return {
        "id": 3,
        "name": "HTLC (claim path: preimage + sig)",
        "witness_rule": "Fixed 5 (Triplets K + Reveal P)",
        "block_types": ["HTLC"],
        "key_seeds": {"recv": seed_recv, "send": seed_send},
        "recv_pubkey_compressed": recv_pk_hex,
        "send_pubkey_compressed": send_pk_hex,
        "preimage_hex": preimage.hex(),
        "payment_hash_hex": payment_hash.hex(),
        "csv_blocks": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_4_csv(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CSV", "fields": [
            {"type": "NUMERIC", "hex": "90000000"},  # 144 blocks LE
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec4")
    return {
        "id": 4,
        "name": "CSV relative-timelock (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["CSV"],
        "csv_blocks": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_5_cltv(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CLTV", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},  # 0 = no actual time-lock
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec5")
    return {
        "id": 5,
        "name": "CLTV absolute-timelock (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["CLTV"],
        "cltv_height": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_6_multisig_2of3(node, wallet) -> dict:
    seeds = ["bip-xxxx-vec6-msig-a", "bip-xxxx-vec6-msig-b", "bip-xxxx-vec6-msig-c"]
    pks = [derive_key(s) for s in seeds]
    pk_hexes = [schnorr_pk_compressed(k).hex() for k in pks]
    # createrungtx for MULTISIG takes the full pubkey list and computes
    # the inner-Merkle pubkey root commit itself (post-E-018a).
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "MULTISIG", "fields": [
            {"type": "NUMERIC", "hex": "02000000"},   # K = 2
            {"type": "SCHEME",  "hex": "01"},          # SCHNORR
            {"type": "PUBKEY",  "hex": pk_hexes[0]},   # canonical sort
            {"type": "PUBKEY",  "hex": pk_hexes[1]},
            {"type": "PUBKEY",  "hex": pk_hexes[2]},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec6")
    return {
        "id": 6,
        "name": "MULTISIG 2-of-3 with inner-Merkle pubkey commit",
        "witness_rule": "Triplets K",
        "block_types": ["MULTISIG"],
        "key_seeds": {f"k{i}": s for i, s in enumerate(seeds)},
        "pubkeys_compressed": pk_hexes,
        "threshold": 2,
        "fund_tx": _shape_fund(fb),
    }


def vec_7_ctv(node, wallet) -> dict:
    # CTV's HASH256 is a template hash; we use a placeholder here
    # because the test fixture documents the wire shape, not a working
    # spend. (A working CTV spend would derive the hash via
    # computectvhash from a fully-specified spending tx template.)
    template_hash = b"\xcc" * 32
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CTV", "fields": [
            {"type": "HASH256", "hex": template_hash.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec7")
    return {
        "id": 7,
        "name": "CTV BIP-119 covenant (Empty witness rule)",
        "witness_rule": "Empty (post-E-023)",
        "block_types": ["CTV"],
        "template_hash_hex": template_hash.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_8_pq_batch_anchor(node, wallet) -> dict:
    # PQ_BATCH conditions = HASH256(falcon_pubkey). For a fund-time
    # vector we only need a deterministic 32-byte commitment — actual
    # FALCON keypair generation is non-deterministic (fresh randomness)
    # and would break byte-equivalence in CI verify mode. The spend-side
    # PQ_BATCH flow (anchor input revealing PUBKEY + SIGNATURE) is
    # exercised separately in test/functional/feature_rung_pq_batch.py.
    # PREIMAGE max = 32 B, so use a 32-byte deterministic placeholder.
    deterministic_pk_seed = hashlib.sha256(
        b"bip-xxxx-vec8-pq-batch-placeholder"
    ).digest()
    commit_hex = hashlib.sha256(deterministic_pk_seed).hexdigest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "PQ_BATCH", "fields": [
            {"type": "PREIMAGE", "hex": deterministic_pk_seed.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec8")
    return {
        "id": 8,
        "name": "PQ_BATCH single-anchor input (deterministic placeholder)",
        "witness_rule": "PQ-anchor",
        "block_types": ["PQ_BATCH"],
        "preimage_seed_hex": deterministic_pk_seed.hex(),
        "commit_sha256_hex": commit_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_10_anchor(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ANCHOR", "fields": [
            {"type": "NUMERIC", "hex": "0a000000"},  # anchor_id = 10
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec10")
    return {
        "id": 10,
        "name": "ANCHOR marker (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["ANCHOR"],
        "anchor_id": 10,
        "fund_tx": _shape_fund(fb),
    }


def vec_11_anchor_channel(node, wallet) -> dict:
    # v0.7 ANCHOR_CHANNEL is a pure marker (commitment_number only, no
    # pubkeys). Closes the E-002 channel of 66 B/spend that the v0.6
    # 2-pubkey shape opened.
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ANCHOR_CHANNEL", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec11")
    return {
        "id": 11,
        "name": "ANCHOR_CHANNEL pure marker (post-E-002)",
        "witness_rule": "Empty",
        "block_types": ["ANCHOR_CHANNEL"],
        "commitment_number": 1,
        "fund_tx": _shape_fund(fb),
    }


def vec_12_amount_lock(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "AMOUNT_LOCK", "fields": [
            {"type": "NUMERIC", "hex": "10270000"},   # min = 10000 sats
            {"type": "NUMERIC", "hex": "00ca9a3b"},   # max = 1_000_000_000 sats
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec12")
    return {
        "id": 12,
        "name": "AMOUNT_LOCK [min, max] band (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["AMOUNT_LOCK"],
        "min_sats": 10000,
        "max_sats": 1_000_000_000,
        "fund_tx": _shape_fund(fb),
    }


def vec_13_tagged_hash(node, wallet) -> dict:
    # BIP-340 tagged hash: conditions carry [HASH256(SHA256(tag)),
    # HASH256(expected)]. We pre-compute both because PREIMAGE auto-
    # conversion would only build the second slot, not the tag commit.
    tag = b"BIP0340/challenge"
    tag_hash = hashlib.sha256(tag).digest()
    preimage = b"\xab" * 16
    expected = hashlib.sha256(tag_hash + tag_hash + preimage).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "TAGGED_HASH", "fields": [
            {"type": "HASH256", "hex": tag_hash.hex()},
            {"type": "HASH256", "hex": expected.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec13")
    return {
        "id": 13,
        "name": "TAGGED_HASH BIP-340 (Reveal P)",
        "witness_rule": "Reveal P",
        "block_types": ["TAGGED_HASH"],
        "tag_utf8": tag.decode(),
        "tag_hash_hex": tag_hash.hex(),
        "preimage_hex": preimage.hex(),
        "expected_hex": expected.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_14_hash_guarded(node, wallet) -> dict:
    preimage = b"vec14-hash-guarded-preimage"
    commit = hashlib.sha256(preimage).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "HASH_GUARDED", "fields": [
            {"type": "PREIMAGE", "hex": preimage.hex()},  # auto → HASH256
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec14")
    return {
        "id": 14,
        "name": "HASH_GUARDED raw SHA256 commit (Reveal P)",
        "witness_rule": "Reveal P",
        "block_types": ["HASH_GUARDED"],
        "preimage_hex": preimage.hex(),
        "commit_hex": commit.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_15_accumulator(node, wallet) -> dict:
    # ACCUMULATOR conditions hold the Merkle root of the membership set;
    # spend reveals one leaf + Merkle proof in the witness. Vector here
    # only documents the fund-time wire shape.
    leaves = [hashlib.sha256(f"acc-leaf-{i}".encode()).digest() for i in range(4)]
    # Simple 4-leaf Merkle root with double-SHA256 internal nodes.
    def _merkle(level):
        while len(level) > 1:
            if len(level) % 2 == 1:
                level.append(level[-1])
            level = [hashlib.sha256(hashlib.sha256(level[i] + level[i+1]).digest()).digest()
                     for i in range(0, len(level), 2)]
        return level[0]
    root = _merkle(list(leaves))
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ACCUMULATOR", "fields": [
            {"type": "HASH256", "hex": root.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec15")
    return {
        "id": 15,
        "name": "ACCUMULATOR Merkle membership root",
        "witness_rule": "Accumulator",
        "block_types": ["ACCUMULATOR"],
        "leaves_hex": [l.hex() for l in leaves],
        "merkle_root_hex": root.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_16_p2sh_legacy(node, wallet) -> dict:
    # P2SH_LEGACY: HASH160-committed inner script. createrungtx accepts
    # SCRIPT_BODY (or PREIMAGE) in conditions and folds to HASH160.
    inner = b"vec16-inner-script"
    commit = ripemd160(hashlib.sha256(inner).digest())
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "P2SH_LEGACY", "fields": [
            {"type": "SCRIPT_BODY", "hex": inner.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec16")
    return {
        "id": 16,
        "name": "P2SH_LEGACY wrapper (HASH160-committed inner script)",
        "witness_rule": "Bridging (legacy P2*)",
        "block_types": ["P2SH_LEGACY"],
        "inner_script_hex": inner.hex(),
        "hash160_hex": commit.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_17_p2wsh_legacy(node, wallet) -> dict:
    inner = b"vec17-witness-script"
    commit = hashlib.sha256(inner).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "P2WSH_LEGACY", "fields": [
            {"type": "SCRIPT_BODY", "hex": inner.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec17")
    return {
        "id": 17,
        "name": "P2WSH_LEGACY wrapper (HASH256-committed inner script)",
        "witness_rule": "Bridging (legacy P2*)",
        "block_types": ["P2WSH_LEGACY"],
        "inner_script_hex": inner.hex(),
        "hash256_hex": commit.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_18_vault_lock(node, wallet) -> dict:
    seed_recovery = "bip-xxxx-vec18-vault-recovery"
    seed_hot = "bip-xxxx-vec18-vault-hot"
    rec_pk = derive_key(seed_recovery)
    hot_pk = derive_key(seed_hot)
    rec_pk_hex = schnorr_pk_compressed(rec_pk).hex()
    hot_pk_hex = schnorr_pk_compressed(hot_pk).hex()
    # Conditions: [NUMERIC(hot_delay)] + 2 PUBKEYs that fold into the
    # Merkle leaf (PubkeyCountForBlock = 2).
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "VAULT_LOCK", "fields": [
            {"type": "NUMERIC", "hex": "90000000"},  # hot_delay = 144 blocks
            {"type": "PUBKEY",  "hex": rec_pk_hex},
            {"type": "PUBKEY",  "hex": hot_pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec18")
    return {
        "id": 18,
        "name": "VAULT_LOCK 2-key vault (Fixed N + 2 PUBKEYs in leaf)",
        "witness_rule": "Fixed N",
        "block_types": ["VAULT_LOCK"],
        "key_seeds": {"recovery": seed_recovery, "hot": seed_hot},
        "recovery_pubkey_compressed": rec_pk_hex,
        "hot_pubkey_compressed": hot_pk_hex,
        "hot_delay": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_19_timelocked_sig(node, wallet) -> dict:
    seed_pk = "bip-xxxx-vec19-tlsig-key"
    pk = derive_key(seed_pk)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "TIMELOCKED_SIG", "fields": [
            {"type": "SCHEME",  "hex": "01"},
            {"type": "NUMERIC", "hex": "90000000"},  # CSV = 144 blocks
            {"type": "PUBKEY",  "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec19")
    return {
        "id": 19,
        "name": "TIMELOCKED_SIG compound (sig + CSV)",
        "witness_rule": "Compound (Fixed N + Empty)",
        "block_types": ["TIMELOCKED_SIG"],
        "key_seed": seed_pk,
        "pubkey_compressed": pk_hex,
        "csv_blocks": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_20_hash_sig(node, wallet) -> dict:
    seed_pk = "bip-xxxx-vec20-hashsig-key"
    pk = derive_key(seed_pk)
    pk_hex = schnorr_pk_compressed(pk).hex()
    preimage = b"vec20-hash-sig-preimage"
    commit = hashlib.sha256(preimage).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "HASH_SIG", "fields": [
            {"type": "PREIMAGE", "hex": preimage.hex()},  # auto → HASH256
            {"type": "SCHEME",   "hex": "01"},
            {"type": "PUBKEY",   "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec20")
    return {
        "id": 20,
        "name": "HASH_SIG compound (preimage + sig)",
        "witness_rule": "Compound (Reveal P + Fixed N)",
        "block_types": ["HASH_SIG"],
        "key_seed": seed_pk,
        "pubkey_compressed": pk_hex,
        "preimage_hex": preimage.hex(),
        "commit_hex": commit.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_21_ptlc(node, wallet) -> dict:
    # PTLC: conditions hold [NUMERIC(CSV)]; the adaptor pubkey folds into
    # the Merkle leaf (PubkeyCountForBlock = 1 post-v0.7). Pure SIG-style
    # witness: [PUBKEY, SIGNATURE] — the adaptor secret enters via the
    # signature, no separate ADAPTOR_POINT field.
    seed_adaptor = "bip-xxxx-vec21-ptlc-adaptor"
    adaptor_pk = derive_key(seed_adaptor)
    adaptor_pk_hex = schnorr_pk_compressed(adaptor_pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "PTLC", "fields": [
            {"type": "NUMERIC", "hex": "90000000"},  # CSV = 144 blocks
            {"type": "PUBKEY",  "hex": adaptor_pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec21")
    return {
        "id": 21,
        "name": "PTLC point-locked HTLC (Fixed N + adaptor in leaf)",
        "witness_rule": "Fixed N",
        "block_types": ["PTLC"],
        "key_seed": seed_adaptor,
        "adaptor_pubkey_compressed": adaptor_pk_hex,
        "csv_blocks": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_22_anchor_fee(node, wallet) -> dict:
    seed_a = "bip-xxxx-vec22-anchorfee-a"
    seed_b = "bip-xxxx-vec22-anchorfee-b"
    pk_a = derive_key(seed_a)
    pk_b = derive_key(seed_b)
    pk_a_hex = schnorr_pk_compressed(pk_a).hex()
    pk_b_hex = schnorr_pk_compressed(pk_b).hex()
    # Conditions: [SCHEME, NUMERIC(min), NUMERIC(max), NUMERIC(weight),
    # NUMERIC(commit)] + 2 PUBKEYs into Merkle leaf.
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ANCHOR_FEE", "fields": [
            {"type": "SCHEME",  "hex": "01"},
            {"type": "NUMERIC", "hex": "01000000"},  # min_fee_rate = 1
            {"type": "NUMERIC", "hex": "64000000"},  # max_fee_rate = 100
            {"type": "NUMERIC", "hex": "a0860100"},  # max_weight = 100000 WU
            {"type": "NUMERIC", "hex": "01000000"},  # commitment_number = 1
            {"type": "PUBKEY",  "hex": pk_a_hex},
            {"type": "PUBKEY",  "hex": pk_b_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec22")
    return {
        "id": 22,
        "name": "ANCHOR_FEE 2-of-2 fee anchor (compound)",
        "witness_rule": "Compound (Fixed N anchor + fee-band)",
        "block_types": ["ANCHOR_FEE"],
        "key_seeds": {"a": seed_a, "b": seed_b},
        "pubkeys_compressed": [pk_a_hex, pk_b_hex],
        "min_fee_rate": 1,
        "max_fee_rate": 100,
        "max_weight": 100_000,
        "commitment_number": 1,
        "fund_tx": _shape_fund(fb),
    }


def vec_23_timelocked_multisig(node, wallet) -> dict:
    seeds = ["bip-xxxx-vec23-tlms-a",
             "bip-xxxx-vec23-tlms-b",
             "bip-xxxx-vec23-tlms-c"]
    pks = [derive_key(s) for s in seeds]
    pk_hexes = [schnorr_pk_compressed(k).hex() for k in pks]
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "TIMELOCKED_MULTISIG", "fields": [
            {"type": "NUMERIC", "hex": "02000000"},  # K = 2
            {"type": "NUMERIC", "hex": "90000000"},  # CSV = 144
            {"type": "SCHEME",  "hex": "01"},
            {"type": "PUBKEY",  "hex": pk_hexes[0]},
            {"type": "PUBKEY",  "hex": pk_hexes[1]},
            {"type": "PUBKEY",  "hex": pk_hexes[2]},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec23")
    return {
        "id": 23,
        "name": "TIMELOCKED_MULTISIG 2-of-3 + CSV (Triplets K + Empty)",
        "witness_rule": "Compound (Triplets K + Empty)",
        "block_types": ["TIMELOCKED_MULTISIG"],
        "key_seeds": {f"k{i}": s for i, s in enumerate(seeds)},
        "pubkeys_compressed": pk_hexes,
        "threshold": 2,
        "csv_blocks": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_24_recurse_same(node, wallet) -> dict:
    # RECURSE_SAME: conditions = [NUMERIC(max_depth)]. Fund only —
    # carry-rule recursion is exercised separately by feature_rung_tx.
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "RECURSE_SAME", "fields": [
            {"type": "NUMERIC", "hex": "05000000"},  # max_depth = 5
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec24")
    return {
        "id": 24,
        "name": "RECURSE_SAME max_depth=5 (Recursion)",
        "witness_rule": "Empty (recursion carry-rule)",
        "block_types": ["RECURSE_SAME"],
        "max_depth": 5,
        "fund_tx": _shape_fund(fb),
    }


def vec_25_output_check(node, wallet) -> dict:
    # OUTPUT_CHECK: pins (output_index, min_sats, max_sats, script_hash).
    # script_hash = SHA256 of a target scriptPubKey (placeholder here).
    target_spk = b"\x00\x14" + (b"\x77" * 20)  # P2WPKH-shaped placeholder
    spk_hash = hashlib.sha256(target_spk).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "OUTPUT_CHECK", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},   # output_index = 1
            {"type": "NUMERIC", "hex": "10270000"},   # min_sats = 10000
            {"type": "NUMERIC", "hex": "00ca9a3b"},   # max_sats = 1_000_000_000
            {"type": "HASH256", "hex": spk_hash.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec25")
    return {
        "id": 25,
        "name": "OUTPUT_CHECK (output index + value band + script hash)",
        "witness_rule": "Empty (introspection)",
        "block_types": ["OUTPUT_CHECK"],
        "output_index_pinned": 1,
        "min_sats": 10000,
        "max_sats": 1_000_000_000,
        "target_spk_hex": target_spk.hex(),
        "spk_hash_hex": spk_hash.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_26_p2pkh_legacy(node, wallet) -> dict:
    seed_pk = "bip-xxxx-vec26-p2pkh-key"
    pk = derive_key(seed_pk)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "P2PKH_LEGACY", "fields": [
            {"type": "PUBKEY", "hex": pk_hex},  # auto → HASH160
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec26")
    return {
        "id": 26,
        "name": "P2PKH_LEGACY (HASH160 of pubkey)",
        "witness_rule": "Bridging (legacy P2*)",
        "block_types": ["P2PKH_LEGACY"],
        "key_seed": seed_pk,
        "p2pkh_pubkey_compressed": pk_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_27_adaptor_sig(node, wallet) -> dict:
    seed_pk = "bip-xxxx-vec27-adaptor-key"
    pk = derive_key(seed_pk)
    pk_hex = schnorr_pk_compressed(pk).hex()
    # ADAPTOR_SIG conditions are pure marker (NO_IMPLICIT). Pubkey folds
    # into the leaf via PubkeyCountForBlock = 1.
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ADAPTOR_SIG", "fields": [
            {"type": "PUBKEY", "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec27")
    return {
        "id": 27,
        "name": "ADAPTOR_SIG marker (Fixed N + adaptor in leaf)",
        "witness_rule": "Fixed N",
        "block_types": ["ADAPTOR_SIG"],
        "key_seed": seed_pk,
        "adaptor_pubkey_compressed": pk_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_28_musig_threshold(node, wallet) -> dict:
    seed_pk = "bip-xxxx-vec28-musig-key"
    pk = derive_key(seed_pk)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "MUSIG_THRESHOLD", "fields": [
            {"type": "NUMERIC", "hex": "03000000"},  # M = 3
            {"type": "NUMERIC", "hex": "05000000"},  # N = 5
            {"type": "PUBKEY",  "hex": pk_hex},      # aggregated MuSig pubkey
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec28")
    return {
        "id": 28,
        "name": "MUSIG_THRESHOLD 3-of-5 (Triplets K + agg pubkey in leaf)",
        "witness_rule": "Triplets K",
        "block_types": ["MUSIG_THRESHOLD"],
        "key_seed": seed_pk,
        "agg_pubkey_compressed": pk_hex,
        "threshold": 3,
        "group_size": 5,
        "fund_tx": _shape_fund(fb),
    }


def vec_29_cosign(node, wallet) -> dict:
    # COSIGN conditions pin a HASH256 commitment to a co-signer's
    # scriptPubKey; spend reveals the matching SPK in the witness.
    spk = b"\x51\x20" + (b"\x33" * 32)  # P2TR-shaped placeholder
    spk_commit = hashlib.sha256(spk).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "COSIGN", "fields": [
            {"type": "HASH256", "hex": spk_commit.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec29")
    return {
        "id": 29,
        "name": "COSIGN scriptPubKey commit (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["COSIGN"],
        "cosigner_spk_hex": spk.hex(),
        "spk_commit_hex": spk_commit.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_30_compare(node, wallet) -> dict:
    # COMPARE conditions: [op, value_b, value_c]. Pure stateless 3-arg
    # comparison block (e.g., op=1: a > b, etc.).
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "COMPARE", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},  # op = 1 (gt)
            {"type": "NUMERIC", "hex": "10270000"},  # value_b = 10000
            {"type": "NUMERIC", "hex": "00ca9a3b"},  # value_c = 1_000_000_000
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec30")
    return {
        "id": 30,
        "name": "COMPARE op=gt (3 NUMERIC, Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["COMPARE"],
        "op": 1,
        "value_b": 10000,
        "value_c": 1_000_000_000,
        "fund_tx": _shape_fund(fb),
    }


def vec_31_epoch_gate(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "EPOCH_GATE", "fields": [
            {"type": "NUMERIC", "hex": "00000100"},  # epoch_start = 65536
            {"type": "NUMERIC", "hex": "00000200"},  # epoch_end = 131072
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec31")
    return {
        "id": 31,
        "name": "EPOCH_GATE [start, end] (governance)",
        "witness_rule": "Empty",
        "block_types": ["EPOCH_GATE"],
        "epoch_start": 65536,
        "epoch_end": 131072,
        "fund_tx": _shape_fund(fb),
    }


def vec_32_weight_limit(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "WEIGHT_LIMIT", "fields": [
            {"type": "NUMERIC", "hex": "a0860100"},  # 100_000 WU
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec32")
    return {
        "id": 32,
        "name": "WEIGHT_LIMIT 100k WU cap (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["WEIGHT_LIMIT"],
        "max_weight": 100_000,
        "fund_tx": _shape_fund(fb),
    }


def vec_33_input_count(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "INPUT_COUNT", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},  # min_inputs = 1
            {"type": "NUMERIC", "hex": "0a000000"},  # max_inputs = 10
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec33")
    return {
        "id": 33,
        "name": "INPUT_COUNT [1, 10] (introspection)",
        "witness_rule": "Empty (introspection)",
        "block_types": ["INPUT_COUNT"],
        "min_inputs": 1,
        "max_inputs": 10,
        "fund_tx": _shape_fund(fb),
    }


def vec_34_output_count(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "OUTPUT_COUNT", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},
            {"type": "NUMERIC", "hex": "0a000000"},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec34")
    return {
        "id": 34,
        "name": "OUTPUT_COUNT [1, 10] (introspection)",
        "witness_rule": "Empty (introspection)",
        "block_types": ["OUTPUT_COUNT"],
        "min_outputs": 1,
        "max_outputs": 10,
        "fund_tx": _shape_fund(fb),
    }


def vec_35_relative_value(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "RELATIVE_VALUE", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},  # numerator = 1
            {"type": "NUMERIC", "hex": "02000000"},  # denominator = 2
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec35")
    return {
        "id": 35,
        "name": "RELATIVE_VALUE 1/2 (output ratio constraint)",
        "witness_rule": "Empty (introspection)",
        "block_types": ["RELATIVE_VALUE"],
        "numerator": 1,
        "denominator": 2,
        "fund_tx": _shape_fund(fb),
    }


def vec_36_anchor_seal(node, wallet) -> dict:
    p1 = b"vec36-seal-a-preimage"
    p2 = b"vec36-seal-b-preimage"
    h1 = hashlib.sha256(p1).digest()
    h2 = hashlib.sha256(p2).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ANCHOR_SEAL", "fields": [
            {"type": "PREIMAGE", "hex": p1.hex()},  # auto → HASH256
            {"type": "PREIMAGE", "hex": p2.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec36")
    return {
        "id": 36,
        "name": "ANCHOR_SEAL pair commit (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["ANCHOR_SEAL"],
        "preimage_a_hex": p1.hex(),
        "preimage_b_hex": p2.hex(),
        "seal_a_hex": h1.hex(),
        "seal_b_hex": h2.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_37_hysteresis_fee(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "HYSTERESIS_FEE", "fields": [
            {"type": "NUMERIC", "hex": "64000000"},  # high = 100 sat/vB
            {"type": "NUMERIC", "hex": "0a000000"},  # low = 10 sat/vB
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec37")
    return {
        "id": 37,
        "name": "HYSTERESIS_FEE high=100/low=10 (PLC family)",
        "witness_rule": "Empty",
        "block_types": ["HYSTERESIS_FEE"],
        "high_sat_vb": 100,
        "low_sat_vb": 10,
        "fund_tx": _shape_fund(fb),
    }


def vec_38_rate_limit(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "RATE_LIMIT", "fields": [
            {"type": "NUMERIC", "hex": "0a000000"},  # max_per_block = 10
            {"type": "NUMERIC", "hex": "64000000"},  # accumulation_cap = 100
            {"type": "NUMERIC", "hex": "90000000"},  # refill_blocks = 144
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec38")
    return {
        "id": 38,
        "name": "RATE_LIMIT 10/block, cap 100, refill 144 blk (PLC family)",
        "witness_rule": "Empty",
        "block_types": ["RATE_LIMIT"],
        "max_per_block": 10,
        "accumulation_cap": 100,
        "refill_blocks": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_39_one_shot(node, wallet) -> dict:
    preimage = b"vec39-one-shot-preimage"
    commit = hashlib.sha256(preimage).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ONE_SHOT", "fields": [
            {"type": "NUMERIC",  "hex": "00000000"},     # state = ARMED
            {"type": "PREIMAGE", "hex": preimage.hex()},  # auto → HASH256
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec39")
    return {
        "id": 39,
        "name": "ONE_SHOT armed + commit (PLC family)",
        "witness_rule": "Empty",
        "block_types": ["ONE_SHOT"],
        "initial_state": 0,
        "preimage_hex": preimage.hex(),
        "commit_hex": commit.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_40_anchor_pool(node, wallet) -> dict:
    preimage = b"vec40-vtxo-tree-preimage"
    vtxo_root = hashlib.sha256(preimage).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ANCHOR_POOL", "fields": [
            {"type": "PREIMAGE", "hex": preimage.hex()},  # auto → HASH256
            {"type": "NUMERIC",  "hex": "07000000"},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec40")
    return {
        "id": 40,
        "name": "ANCHOR_POOL VTXO tree marker (PLC family)",
        "witness_rule": "Empty",
        "block_types": ["ANCHOR_POOL"],
        "preimage_hex": preimage.hex(),
        "vtxo_tree_root_hex": vtxo_root.hex(),
        "participant_count": 7,
        "fund_tx": _shape_fund(fb),
    }


def vec_41_anchor_reserve(node, wallet) -> dict:
    preimage = b"vec41-guardian-preimage"
    guardian = hashlib.sha256(preimage).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ANCHOR_RESERVE", "fields": [
            {"type": "NUMERIC",  "hex": "02000000"},
            {"type": "NUMERIC",  "hex": "03000000"},
            {"type": "PREIMAGE", "hex": preimage.hex()},  # auto → HASH256
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec41")
    return {
        "id": 41,
        "name": "ANCHOR_RESERVE 2-of-3 guardian (PLC family)",
        "witness_rule": "Empty",
        "block_types": ["ANCHOR_RESERVE"],
        "threshold_n": 2,
        "threshold_m": 3,
        "preimage_hex": preimage.hex(),
        "guardian_hash_hex": guardian.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_42_anchor_oracle(node, wallet) -> dict:
    seed_pk = "bip-xxxx-vec42-oracle-key"
    pk = derive_key(seed_pk)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "ANCHOR_ORACLE", "fields": [
            {"type": "NUMERIC", "hex": "03000000"},  # outcome_count = 3
            {"type": "PUBKEY",  "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec42")
    return {
        "id": 42,
        "name": "ANCHOR_ORACLE 3-outcome (PLC + oracle pubkey in leaf)",
        "witness_rule": "Fixed N",
        "block_types": ["ANCHOR_ORACLE"],
        "key_seed": seed_pk,
        "oracle_pubkey_compressed": pk_hex,
        "outcome_count": 3,
        "fund_tx": _shape_fund(fb),
    }


def vec_43_recurse_until(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "RECURSE_UNTIL", "fields": [
            {"type": "NUMERIC", "hex": "40420f00"},  # until_height = 1_000_000
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec43")
    return {
        "id": 43,
        "name": "RECURSE_UNTIL height (Recursion family)",
        "witness_rule": "Empty (recursion carry-rule)",
        "block_types": ["RECURSE_UNTIL"],
        "until_height": 1_000_000,
        "fund_tx": _shape_fund(fb),
    }


def vec_44_recurse_count(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "RECURSE_COUNT", "fields": [
            {"type": "NUMERIC", "hex": "0a000000"},  # max_count = 10
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec44")
    return {
        "id": 44,
        "name": "RECURSE_COUNT max=10 (Recursion family)",
        "witness_rule": "Empty (recursion carry-rule)",
        "block_types": ["RECURSE_COUNT"],
        "max_count": 10,
        "fund_tx": _shape_fund(fb),
    }


def vec_45_recurse_split(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "RECURSE_SPLIT", "fields": [
            {"type": "NUMERIC", "hex": "04000000"},  # max_splits = 4
            {"type": "NUMERIC", "hex": "10270000"},  # min_split_sats = 10_000
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec45")
    return {
        "id": 45,
        "name": "RECURSE_SPLIT 4-way ≥ 10k sats (Recursion family)",
        "witness_rule": "Empty (recursion carry-rule)",
        "block_types": ["RECURSE_SPLIT"],
        "max_splits": 4,
        "min_split_sats": 10_000,
        "fund_tx": _shape_fund(fb),
    }


def vec_46_latch_set(node, wallet) -> dict:
    seed_pk = "bip-xxxx-vec46-latch-set-key"
    pk = derive_key(seed_pk)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "LATCH_SET", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},  # state = 0 (UNSET)
            {"type": "PUBKEY",  "hex": pk_hex},      # setter key in leaf
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec46")
    return {
        "id": 46,
        "name": "LATCH_SET state=0 (PLC + setter key in leaf)",
        "witness_rule": "Fixed N",
        "block_types": ["LATCH_SET"],
        "key_seed": seed_pk,
        "setter_pubkey_compressed": pk_hex,
        "initial_state": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_47_p2tr_script_legacy(node, wallet) -> dict:
    seed_pk = "bip-xxxx-vec47-p2tr-internal"
    pk = derive_key(seed_pk)
    pk_hex = schnorr_pk_compressed(pk).hex()
    inner = b"vec47-tap-leaf-script"
    leaf_commit = hashlib.sha256(inner).digest()
    # P2TR_SCRIPT_LEGACY: HASH256 (script-leaf commit) + 1 PUBKEY in
    # Merkle leaf (internal key, PubkeyCountForBlock = 1).
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "P2TR_SCRIPT_LEGACY", "fields": [
            {"type": "SCRIPT_BODY", "hex": inner.hex()},  # auto → HASH256
            {"type": "PUBKEY",      "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec47")
    return {
        "id": 47,
        "name": "P2TR_SCRIPT_LEGACY wrapper (script leaf + internal key)",
        "witness_rule": "Bridging (legacy P2*)",
        "block_types": ["P2TR_SCRIPT_LEGACY"],
        "key_seed": seed_pk,
        "internal_pubkey_compressed": pk_hex,
        "leaf_script_hex": inner.hex(),
        "leaf_commit_hex": leaf_commit.hex(),
        "fund_tx": _shape_fund(fb),
    }


# ──────────────────────────────────────────────────────────────────
# Edge-case vectors (boundary values within positive range)
# ──────────────────────────────────────────────────────────────────


def vec_48_multisig_1of1(node, wallet) -> dict:
    seed = "bip-xxxx-vec48-msig-solo"
    pk = derive_key(seed)
    pk_hex = schnorr_pk_compressed(pk).hex()
    # Edge: K = N = 1. Inner pubkey-Merkle root over a single pubkey
    # collapses to a 1-leaf tree (still committed).
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "MULTISIG", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},
            {"type": "SCHEME",  "hex": "01"},
            {"type": "PUBKEY",  "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec48")
    return {
        "id": 48,
        "name": "MULTISIG 1-of-1 (boundary K=N=1)",
        "witness_rule": "Triplets K (boundary)",
        "block_types": ["MULTISIG"],
        "key_seed": seed,
        "pubkeys_compressed": [pk_hex],
        "threshold": 1,
        "fund_tx": _shape_fund(fb),
    }


def vec_49_amount_lock_point(node, wallet) -> dict:
    # Edge: min == max. Band collapses to a single-value pin.
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "AMOUNT_LOCK", "fields": [
            {"type": "NUMERIC", "hex": "10270000"},
            {"type": "NUMERIC", "hex": "10270000"},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec49")
    return {
        "id": 49,
        "name": "AMOUNT_LOCK min == max (boundary, point-pin)",
        "witness_rule": "Empty (boundary)",
        "block_types": ["AMOUNT_LOCK"],
        "min_sats": 10_000,
        "max_sats": 10_000,
        "fund_tx": _shape_fund(fb),
    }


def vec_50_csv_zero(node, wallet) -> dict:
    # Edge: CSV = 0. Lowest valid relative timelock — effectively no
    # delay. Useful for testing CSV evaluator's zero-handling path.
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CSV", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec50")
    return {
        "id": 50,
        "name": "CSV = 0 (boundary, lowest valid relative timelock)",
        "witness_rule": "Empty (boundary)",
        "block_types": ["CSV"],
        "csv_blocks": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_51_p2pk_legacy(node, wallet) -> dict:
    """P2PK_LEGACY: pubkey-only legacy wrapper. Conditions = [SCHEME];
    PUBKEY folds into the Merkle leaf (PubkeyCountForBlock = 1)."""
    seed = "bip-xxxx-vec51-p2pk-key"
    pk = derive_key(seed)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "P2PK_LEGACY", "fields": [
            {"type": "SCHEME", "hex": "01"},
            {"type": "PUBKEY", "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec51")
    return {
        "id": 51,
        "name": "P2PK_LEGACY (raw pubkey, SCHEME-only conditions)",
        "witness_rule": "Bridging (legacy P2*)",
        "block_types": ["P2PK_LEGACY"],
        "key_seed": seed,
        "p2pk_pubkey_compressed": pk_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_52_p2tr_legacy(node, wallet) -> dict:
    """P2TR_LEGACY: BIP-341 key-path wrapper. Same shape as P2PK_LEGACY
    at fund time — distinct evaluator at spend time (taproot key-path
    sig vs raw ECDSA/Schnorr)."""
    seed = "bip-xxxx-vec52-p2tr-key"
    pk = derive_key(seed)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "P2TR_LEGACY", "fields": [
            {"type": "SCHEME", "hex": "01"},
            {"type": "PUBKEY", "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec52")
    return {
        "id": 52,
        "name": "P2TR_LEGACY (BIP-341 key-path wrapper)",
        "witness_rule": "Bridging (legacy P2*)",
        "block_types": ["P2TR_LEGACY"],
        "key_seed": seed,
        "p2tr_pubkey_compressed": pk_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_53_key_ref_sig(node, wallet) -> dict:
    """KEY_REF_SIG: pubkey is dereferenced from a relay block at spend
    time. Conditions = [NUMERIC(relay_index), NUMERIC(block_index)].
    Fund-time only validates the indices; the relay must exist at
    spend."""
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "KEY_REF_SIG", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},  # relay_index = 0
            {"type": "NUMERIC", "hex": "00000000"},  # block_index = 0
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec53")
    return {
        "id": 53,
        "name": "KEY_REF_SIG (relay 0, block 0)",
        "witness_rule": "Fixed N (deferred via relay reference)",
        "block_types": ["KEY_REF_SIG"],
        "relay_index": 0,
        "block_index": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_54_csv_time(node, wallet) -> dict:
    """CSV_TIME: median-time-past relative timelock. NUMERIC bit-22
    set selects the time-based variant per BIP-68 (we're funding a
    raw structural value here; spend semantics enforce time)."""
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CSV_TIME", "fields": [
            {"type": "NUMERIC", "hex": "10000000"},  # 16 (small structural value)
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec54")
    return {
        "id": 54,
        "name": "CSV_TIME relative-timelock (median-time-past)",
        "witness_rule": "Empty",
        "block_types": ["CSV_TIME"],
        "csv_time_value": 16,
        "fund_tx": _shape_fund(fb),
    }


def vec_55_cltv_time(node, wallet) -> dict:
    """CLTV_TIME: absolute MTP timelock."""
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CLTV_TIME", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec55")
    return {
        "id": 55,
        "name": "CLTV_TIME absolute-timelock (median-time-past)",
        "witness_rule": "Empty",
        "block_types": ["CLTV_TIME"],
        "cltv_time_value": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_56_hysteresis_value(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "HYSTERESIS_VALUE", "fields": [
            {"type": "NUMERIC", "hex": "00ca9a3b"},  # high = 1B sats
            {"type": "NUMERIC", "hex": "10270000"},  # low = 10k sats
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec56")
    return {
        "id": 56,
        "name": "HYSTERESIS_VALUE high=1B/low=10k sats (PLC)",
        "witness_rule": "Empty",
        "block_types": ["HYSTERESIS_VALUE"],
        "high_sats": 1_000_000_000,
        "low_sats": 10_000,
        "fund_tx": _shape_fund(fb),
    }


def vec_57_timer_continuous(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "TIMER_CONTINUOUS", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},  # accumulated = 0
            {"type": "NUMERIC", "hex": "90000000"},  # target = 144
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec57")
    return {
        "id": 57,
        "name": "TIMER_CONTINUOUS accumulated=0/target=144 (PLC)",
        "witness_rule": "Empty",
        "block_types": ["TIMER_CONTINUOUS"],
        "accumulated": 0,
        "target": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_58_timer_off_delay(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "TIMER_OFF_DELAY", "fields": [
            {"type": "NUMERIC", "hex": "20030000"},  # remaining = 800
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec58")
    return {
        "id": 58,
        "name": "TIMER_OFF_DELAY remaining=800 (PLC)",
        "witness_rule": "Empty",
        "block_types": ["TIMER_OFF_DELAY"],
        "remaining": 800,
        "fund_tx": _shape_fund(fb),
    }


def vec_59_latch_reset(node, wallet) -> dict:
    seed = "bip-xxxx-vec59-latch-reset-key"
    pk = derive_key(seed)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "LATCH_RESET", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},  # state = SET
            {"type": "NUMERIC", "hex": "0a000000"},  # delay = 10
            {"type": "PUBKEY",  "hex": pk_hex},      # resetter in leaf
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec59")
    return {
        "id": 59,
        "name": "LATCH_RESET state=SET, delay=10 (PLC + resetter key)",
        "witness_rule": "Fixed N",
        "block_types": ["LATCH_RESET"],
        "key_seed": seed,
        "resetter_pubkey_compressed": pk_hex,
        "current_state": 1,
        "delay": 10,
        "fund_tx": _shape_fund(fb),
    }


def vec_60_counter_down(node, wallet) -> dict:
    seed = "bip-xxxx-vec60-counter-down-key"
    pk = derive_key(seed)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "COUNTER_DOWN", "fields": [
            {"type": "NUMERIC", "hex": "0a000000"},  # count = 10
            {"type": "PUBKEY",  "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec60")
    return {
        "id": 60,
        "name": "COUNTER_DOWN count=10 (PLC + event signer)",
        "witness_rule": "Fixed N",
        "block_types": ["COUNTER_DOWN"],
        "key_seed": seed,
        "event_signer_pubkey_compressed": pk_hex,
        "count": 10,
        "fund_tx": _shape_fund(fb),
    }


def vec_61_counter_preset(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "COUNTER_PRESET", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},  # current = 0
            {"type": "NUMERIC", "hex": "05000000"},  # preset = 5
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec61")
    return {
        "id": 61,
        "name": "COUNTER_PRESET current=0/preset=5 (PLC, no key)",
        "witness_rule": "Empty",
        "block_types": ["COUNTER_PRESET"],
        "current": 0,
        "preset": 5,
        "fund_tx": _shape_fund(fb),
    }


def vec_62_counter_up(node, wallet) -> dict:
    seed = "bip-xxxx-vec62-counter-up-key"
    pk = derive_key(seed)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "COUNTER_UP", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},  # current = 0
            {"type": "NUMERIC", "hex": "0a000000"},  # target = 10
            {"type": "PUBKEY",  "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec62")
    return {
        "id": 62,
        "name": "COUNTER_UP current=0/target=10 (PLC + event signer)",
        "witness_rule": "Fixed N",
        "block_types": ["COUNTER_UP"],
        "key_seed": seed,
        "event_signer_pubkey_compressed": pk_hex,
        "current": 0,
        "target": 10,
        "fund_tx": _shape_fund(fb),
    }


def vec_63_sequencer(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "SEQUENCER", "fields": [
            {"type": "NUMERIC", "hex": "01000000"},  # current_step = 1
            {"type": "NUMERIC", "hex": "07000000"},  # total_steps = 7
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec63")
    return {
        "id": 63,
        "name": "SEQUENCER current=1/total=7 (PLC, no key)",
        "witness_rule": "Empty",
        "block_types": ["SEQUENCER"],
        "current_step": 1,
        "total_steps": 7,
        "fund_tx": _shape_fund(fb),
    }


def vec_64_recurse_modified(node, wallet) -> dict:
    """RECURSE_MODIFIED: re-encumber with a single mutation. Conditions
    layout is variable (2 + 4*N where N = mutation count). Minimal
    valid form is the [max_depth, mutation_count] header alone with
    no mutations attached (header still binds the covenant)."""
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "RECURSE_MODIFIED", "fields": [
            {"type": "NUMERIC", "hex": "05000000"},  # max_depth = 5
            {"type": "NUMERIC", "hex": "00000000"},  # mutation_count = 0
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec64")
    return {
        "id": 64,
        "name": "RECURSE_MODIFIED header (max_depth=5, no mutations)",
        "witness_rule": "Empty (recursion carry-rule, leaf-mutating)",
        "block_types": ["RECURSE_MODIFIED"],
        "max_depth": 5,
        "mutation_count": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_65_recurse_decay(node, wallet) -> dict:
    """RECURSE_DECAY: parameter decay covenant. Same variable layout
    as RECURSE_MODIFIED."""
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "RECURSE_DECAY", "fields": [
            {"type": "NUMERIC", "hex": "0a000000"},  # max_depth = 10
            {"type": "NUMERIC", "hex": "00000000"},  # decay_count = 0
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec65")
    return {
        "id": 65,
        "name": "RECURSE_DECAY header (max_depth=10, no decays)",
        "witness_rule": "Empty (recursion carry-rule, leaf-mutating)",
        "block_types": ["RECURSE_DECAY"],
        "max_depth": 10,
        "decay_count": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_19b_cltv_sig(node, wallet) -> dict:
    """CLTV_SIG: SIG + CLTV combined (absolute-time signed). Same
    layout as TIMELOCKED_SIG but the NUMERIC is interpreted as an
    absolute nLockTime instead of a relative CSV."""
    seed = "bip-xxxx-vec19b-cltvsig-key"
    pk = derive_key(seed)
    pk_hex = schnorr_pk_compressed(pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CLTV_SIG", "fields": [
            {"type": "SCHEME",  "hex": "01"},
            {"type": "NUMERIC", "hex": "00000000"},  # nLockTime = 0
            {"type": "PUBKEY",  "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec19b")
    return {
        "id": 68,
        "name": "CLTV_SIG (sig + absolute height nLockTime=0)",
        "witness_rule": "Compound (Fixed N + Empty)",
        "block_types": ["CLTV_SIG"],
        "key_seed": seed,
        "pubkey_compressed": pk_hex,
        "cltv_height": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_66_qabi_prime(node, wallet) -> dict:
    """QABI_PRIME: priming state transition. Conditions = NO_IMPLICIT
    (no committed fields — purely witness-driven). The fund-time wire
    shape is just the block-type header with an empty fields vector."""
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "QABI_PRIME", "fields": []}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec66")
    return {
        "id": 66,
        "name": "QABI_PRIME header (no committed fields)",
        "witness_rule": "PQ-anchor (witness-driven)",
        "block_types": ["QABI_PRIME"],
        "fund_tx": _shape_fund(fb),
    }


def vec_67_qabi_spend(node, wallet) -> dict:
    """QABI_SPEND: batch-spend covenant. Conditions =
    [HASH256(auth_tip), HASH256(committed_root), NUMERIC(depth),
    NUMERIC(expiry), PUBKEY_COMMIT(owner_id)]. PUBKEY_COMMIT outside
    QABI_SPEND is rejected — this is the one carve-out."""
    auth_tip = hashlib.sha256(b"vec67-auth-tip").digest()
    committed_root = b"\x00" * 32  # 0 = unprimed
    owner_pk = derive_key("bip-xxxx-vec67-qabi-owner")
    owner_id = hashlib.sha256(schnorr_pk_compressed(owner_pk)).digest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "QABI_SPEND", "fields": [
            {"type": "HASH256",       "hex": auth_tip.hex()},
            {"type": "HASH256",       "hex": committed_root.hex()},
            {"type": "NUMERIC",       "hex": "00000000"},  # depth = 0
            {"type": "NUMERIC",       "hex": "40420f00"},  # expiry = 1_000_000
            {"type": "PUBKEY_COMMIT", "hex": owner_id.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec67")
    return {
        "id": 67,
        "name": "QABI_SPEND batch covenant (auth_tip + owner_id)",
        "witness_rule": "PQ-anchor (compound)",
        "block_types": ["QABI_SPEND"],
        "auth_tip_hex": auth_tip.hex(),
        "committed_root_hex": committed_root.hex(),
        "depth": 0,
        "expiry": 1_000_000,
        "owner_id_hex": owner_id.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_9_data_return(node, wallet) -> dict:
    # DATA_RETURN: 8-byte nValue == 0 + payload up to 40 bytes on the
    # wire. createrungtx accepts the data field directly.
    payload = b"vec9-data-return-fixture-test"
    assert len(payload) <= 40
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "DATA_RETURN", "fields": [
            {"type": "DATA", "hex": payload.hex()},
        ]}],
    }]
    # DATA_RETURN funds with nValue = 0 — we need ONE non-DATA_RETURN
    # output (any v4 output) to satisfy the per-tx "every output has at
    # least one rung" check. Use a SIG rung at output_index=1 that
    # carries a single-block SIG with a placeholder pubkey.
    placeholder_pk = derive_key("bip-xxxx-vec9-placeholder").get_pubkey().get_bytes().hex()
    rungs.append({
        "output_index": 1,
        "blocks": [{"type": "SIG", "fields": [
            {"type": "SCHEME", "hex": "01"},
            {"type": "PUBKEY", "hex": placeholder_pk},
        ]}],
    })
    utxo = wallet.get_utxo()
    spendable_amt = (Decimal(str(utxo["value"])) - Decimal("0.002")).quantize(Decimal("0.00000001"))
    result = node.createrungtx(
        [{"txid": utxo["txid"], "vout": utxo["vout"]}],
        [Decimal("0.00000000"), spendable_amt],
        rungs,
    )
    tx = tx_from_hex(result["hex"])
    wallet.sign_tx(tx)
    signed_hex = tx.serialize().hex()
    txid = node.sendrawtransaction(signed_hex)
    return {
        "id": 9,
        "name": "DATA_RETURN payload + SIG vout (Unspendable witness rule)",
        "witness_rule": "Unspendable",
        "block_types": ["DATA_RETURN", "SIG"],
        "data_return_payload_hex": payload.hex(),
        "data_return_payload_len": len(payload),
        "fund_tx": {
            "txid": txid,
            "hex": signed_hex,
            "size_bytes": len(signed_hex) // 2,
            "mlsc_scriptpubkey": result["scriptPubKey"],
            "conditions_root": result["conditions_root"],
            "vouts": 2,
        },
    }


def _shape_fund(fb: dict) -> dict:
    """Convert _fund_and_capture's bundle to the spec's fund_tx schema."""
    out = {
        "txid": fb["fund_txid"],
        "hex": fb["fund_hex"],
        "size_bytes": fb["fund_size_bytes"],
        "mlsc_scriptpubkey": fb["mlsc_scriptpubkey"],
        "mlsc_value_btc": fb["mlsc_value_btc"],
        "conditions_root": fb["conditions_root"],
        "key_path": fb["key_path"],
    }
    if fb.get("merkle_root"):
        out["merkle_root"] = fb["merkle_root"]
    if fb.get("internal_pubkey"):
        out["internal_pubkey"] = fb["internal_pubkey"]
    return out


# ──────────────────────────────────────────────────────────────────
# Generator entry
# ──────────────────────────────────────────────────────────────────

class GenerateRungTxVectors(BitcoinTestFramework):
    def set_test_params(self):
        self.num_nodes = 1
        self.setup_clean_chain = True
        self.noban_tx_relay = True

    def run_test(self):
        node = self.nodes[0]
        wallet = MiniWallet(node)
        self.generate(wallet, COINBASE_MATURITY + 20)

        builders = [
            vec_1_sig_keypath,
            vec_2_p2wpkh_legacy,
            vec_3_htlc,
            vec_4_csv,
            vec_5_cltv,
            vec_6_multisig_2of3,
            vec_7_ctv,
            vec_8_pq_batch_anchor,
            vec_9_data_return,
            vec_10_anchor,
            vec_11_anchor_channel,
            vec_12_amount_lock,
            vec_13_tagged_hash,
            vec_14_hash_guarded,
            vec_15_accumulator,
            vec_16_p2sh_legacy,
            vec_17_p2wsh_legacy,
            vec_18_vault_lock,
            vec_19_timelocked_sig,
            vec_20_hash_sig,
            vec_21_ptlc,
            vec_22_anchor_fee,
            vec_23_timelocked_multisig,
            vec_24_recurse_same,
            vec_25_output_check,
            vec_26_p2pkh_legacy,
            vec_27_adaptor_sig,
            vec_28_musig_threshold,
            vec_29_cosign,
            vec_30_compare,
            vec_31_epoch_gate,
            vec_32_weight_limit,
            vec_33_input_count,
            vec_34_output_count,
            vec_35_relative_value,
            vec_36_anchor_seal,
            vec_37_hysteresis_fee,
            vec_38_rate_limit,
            vec_39_one_shot,
            vec_40_anchor_pool,
            vec_41_anchor_reserve,
            vec_42_anchor_oracle,
            vec_43_recurse_until,
            vec_44_recurse_count,
            vec_45_recurse_split,
            vec_46_latch_set,
            vec_47_p2tr_script_legacy,
            vec_48_multisig_1of1,
            vec_49_amount_lock_point,
            vec_50_csv_zero,
            vec_51_p2pk_legacy,
            vec_52_p2tr_legacy,
            vec_53_key_ref_sig,
            vec_54_csv_time,
            vec_55_cltv_time,
            vec_56_hysteresis_value,
            vec_57_timer_continuous,
            vec_58_timer_off_delay,
            vec_59_latch_reset,
            vec_60_counter_down,
            vec_61_counter_preset,
            vec_62_counter_up,
            vec_63_sequencer,
            vec_64_recurse_modified,
            vec_65_recurse_decay,
            vec_66_qabi_prime,
            vec_67_qabi_spend,
            vec_19b_cltv_sig,
        ]
        vectors = []
        for builder in builders:
            try:
                v = builder(node, wallet)
                if v is None:
                    self.log.info(f"  {builder.__name__}: skipped")
                    continue
                vectors.append(v)
                self.generate(node, 1)
                self.log.info(f"  {builder.__name__}: ok (id {v['id']})")
            except Exception as e:
                self.log.error(f"  {builder.__name__}: FAILED — {e}")
                raise

        write_vectors(
            vectors,
            "Reproducible v4 RUNG_TX fund (and where applicable spend) "
            "transaction vectors. Generated by "
            "test/functional/generate_rung_tx_vectors.py — re-run to "
            "regenerate. Covers all 65 core block types across 67 "
            "vectors and the eight witness-rule families: Fixed N, "
            "Bridging, Reveal P, Triplets K, Empty, PQ-anchor, "
            "Unspendable, Accumulator, plus Compound combinations. "
            "Vectors 48-50 are boundary cases (1-of-1 multisig, "
            "point-pin amount band, CSV=0). Vectors 66-67 cover "
            "QABI_PRIME / QABI_SPEND (require build with "
            "ENABLE_QABIO=ON). Negative vectors are in "
            "rung_tx_neg_vectors.json; round-trip spend vectors are "
            "in rung_tx_spend_vectors.json — this file is positive "
            "fund-only.",
        )

        self.log.info(f"Generated {len(vectors)} vectors → {OUTPUT_PATH}")


if __name__ == "__main__":
    GenerateRungTxVectors(__file__).main()
