#!/usr/bin/env python3
# Copyright (c) 2026 The Bitcoin Core developers
# Copyright (c) 2026 defenwycke
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit/.
"""Generate src/test/data/rung_tx_neg_vectors.json — reproducible v4
RUNG_TX rejection vectors.

Each vector documents a malformed createrungtx input that the node must
reject at fund time, along with the exact JSON-RPC error substring the
node returns. Independent implementations should reproduce both the
rejection and the error category.

Run:
    python3 test/functional/generate_rung_tx_neg_vectors.py

Categories covered:
  - Wrong field count (missing or extra fields)
  - Wrong field type (NUMERIC where HASH256 expected, etc.)
  - Wrong field order (CLTV_SIG: [NUMERIC, SCHEME] swapped)
  - Raw HASH256/HASH160 in non-whitelisted blocks (must use PREIMAGE)
  - DATA in non-DATA_RETURN blocks
  - PUBKEY_COMMIT outside QABI_SPEND
  - DATA_RETURN payload exceeding 40 B
  - MULTISIG over MAX_PUBKEYS_PER_MULTISIG (= 16)
  - MULTISIG with no PUBKEYs
  - Empty rung blocks list
"""

import json
import os
import sys
from decimal import Decimal
from pathlib import Path

from test_framework.blocktools import COINBASE_MATURITY
from test_framework.test_framework import BitcoinTestFramework
from test_framework.wallet import MiniWallet


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "src" / "test" / "data" / "rung_tx_neg_vectors.json"


def write_or_verify_vectors(vectors: list, source_description: str):
    """Default behaviour is VERIFY: compare regenerated bytes to the
    committed fixture and fail on drift. With `VECTORS_REGENERATE=1`
    in the environment, overwrite the committed fixture instead."""
    payload = {
        "version": 1,
        "description": source_description,
        "vectors": vectors,
    }
    new_text = json.dumps(payload, indent=2) + "\n"
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    if os.environ.get("VECTORS_REGENERATE") == "1":
        tmp = OUTPUT_PATH.with_suffix(".json.tmp")
        tmp.write_text(new_text)
        tmp.replace(OUTPUT_PATH)
        print(f"wrote {len(vectors)} negative vectors -> {OUTPUT_PATH}")
        return

    if not OUTPUT_PATH.exists():
        raise AssertionError(
            f"{OUTPUT_PATH} does not exist; "
            f"run with VECTORS_REGENERATE=1 to create it"
        )
    existing_text = OUTPUT_PATH.read_text()
    if existing_text == new_text:
        print(f"verified {len(vectors)} negative vectors == "
              f"{OUTPUT_PATH.name}")
        return

    import difflib
    diff_lines = list(difflib.unified_diff(
        existing_text.splitlines(), new_text.splitlines(),
        fromfile=f"committed/{OUTPUT_PATH.name}",
        tofile="regenerated",
        n=2,
        lineterm="",
    ))
    diff = "\n".join(diff_lines[:80])
    raise AssertionError(
        f"FIXTURE DRIFT in {OUTPUT_PATH.name}: regenerated bytes "
        f"differ from committed file. If this is intentional, "
        f"re-run with VECTORS_REGENERATE=1.\n\n{diff}\n"
        f"(diff truncated; first 80 lines)"
    )


write_vectors = write_or_verify_vectors


# Each case: id, name, category, block specs, expected_error_substring.
CASES = [
    # ─── Field count mismatches ───
    {
        "id": 1,
        "name": "SIG with extra NUMERIC after SCHEME",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "SIG", "fields": [
                {"type": "SCHEME",  "hex": "01"},
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "PUBKEY",  "hex": "02" + "11"*32},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 2,
        "name": "MULTISIG missing all PUBKEYs",
        "category": "MULTISIG no pubkeys",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "MULTISIG", "fields": [
                {"type": "NUMERIC", "hex": "02000000"},
                {"type": "SCHEME",  "hex": "01"},
            ]}],
        }],
        "expected_error_substring": "requires at least one PUBKEY",
    },
    {
        "id": 3,
        "name": "AMOUNT_LOCK with single NUMERIC (missing max)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "AMOUNT_LOCK", "fields": [
                {"type": "NUMERIC", "hex": "10270000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    # ─── Field type / order mismatches ───
    {
        "id": 4,
        "name": "CLTV_SIG with [NUMERIC, SCHEME] order swapped",
        "category": "field order mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "CLTV_SIG", "fields": [
                {"type": "NUMERIC", "hex": "00000000"},
                {"type": "SCHEME",  "hex": "01"},
                # Need a PUBKEY too to reach the right field count, but
                # we want the order check to fire first. With layout
                # [SCHEME, NUMERIC] expected, a PUBKEY at index 2 still
                # leaves slot 0 wrong (NUMERIC vs SCHEME).
                {"type": "PUBKEY", "hex": "02" + "11"*32},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    # ─── Raw hash rejection (must use PREIMAGE) ───
    {
        "id": 5,
        "name": "ANCHOR_SEAL with raw HASH256 (must use PREIMAGE)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR_SEAL", "fields": [
                {"type": "HASH256", "hex": "aa"*32},
                {"type": "HASH256", "hex": "bb"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH256",
    },
    {
        "id": 6,
        "name": "HASH_SIG with raw HASH256 (must use PREIMAGE)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "HASH_SIG", "fields": [
                {"type": "HASH256", "hex": "aa"*32},
                {"type": "SCHEME",  "hex": "01"},
                {"type": "PUBKEY",  "hex": "02" + "11"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH256",
    },
    {
        "id": 7,
        "name": "P2WPKH_LEGACY with raw HASH160 (must use PUBKEY)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "P2WPKH_LEGACY", "fields": [
                {"type": "HASH160", "hex": "cc"*20},
            ]}],
        }],
        "expected_error_substring": "Use PUBKEY instead of HASH160",
    },
    # ─── Data type whitelist ───
    {
        "id": 8,
        "name": "ANCHOR with DATA (DATA only allowed in DATA_RETURN)",
        "category": "DATA outside DATA_RETURN",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR", "fields": [
                {"type": "DATA", "hex": "deadbeef"},
            ]}],
        }],
        # Layout check fires first: ANCHOR layout = [NUMERIC], got DATA.
        "expected_error_substring": "type mismatch",
    },
    {
        "id": 9,
        "name": "SIG with PUBKEY_COMMIT (only QABI_SPEND allows it)",
        "category": "PUBKEY_COMMIT outside QABI_SPEND",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "SIG", "fields": [
                {"type": "SCHEME",        "hex": "01"},
                {"type": "PUBKEY_COMMIT", "hex": "ee"*32},
            ]}],
        }],
        "expected_error_substring": "PUBKEY_COMMIT is only allowed",
    },
    # ─── DATA_RETURN payload limits ───
    {
        "id": 10,
        "name": "DATA_RETURN with 41-byte payload (max 40)",
        "category": "DATA_RETURN payload too large",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "DATA_RETURN", "fields": [
                {"type": "DATA", "hex": "ab" * 41},
            ]}],
        }],
        "expected_error_substring": "DATA",
    },
    # ─── MULTISIG cap ───
    {
        "id": 11,
        "name": "MULTISIG with 17 PUBKEYs (max 16)",
        "category": "MULTISIG over MAX_PUBKEYS",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "MULTISIG", "fields": (
                [{"type": "NUMERIC", "hex": "02000000"},
                 {"type": "SCHEME",  "hex": "01"}] +
                [{"type": "PUBKEY", "hex": f"02{i:064x}"} for i in range(1, 18)]
            )}],
        }],
        "expected_error_substring": "max 16",
    },
    # ─── Empty rung ───
    {
        "id": 12,
        "name": "CSV with PREIMAGE (auto → HASH256, NUMERIC expected)",
        "category": "field type mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "CSV", "fields": [
                {"type": "PREIMAGE", "hex": "ab"*16},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    {
        "id": 13,
        "name": "VAULT_LOCK with HASH256 instead of NUMERIC",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "VAULT_LOCK", "fields": [
                {"type": "HASH256", "hex": "aa"*32},
                {"type": "PUBKEY",  "hex": "02" + "11"*32},
                {"type": "PUBKEY",  "hex": "02" + "22"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH256",
    },
    # ─── CTV needs HASH256, not PREIMAGE auto-conversion result mismatch ───
    {
        "id": 14,
        "name": "CTV missing HASH256 field",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "CTV", "fields": []}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    # ─── ACCUMULATOR needs HASH256 root, not NUMERIC ───
    {
        "id": 15,
        "name": "ACCUMULATOR with NUMERIC instead of HASH256",
        "category": "field type mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ACCUMULATOR", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    # ─── COMPARE wrong field count (3 NUMERICs needed) ───
    {
        "id": 16,
        "name": "COMPARE with only 2 NUMERIC (needs 3)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "COMPARE", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "NUMERIC", "hex": "02000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    # ─── HTLC missing path indicator chain ───
    {
        "id": 17,
        "name": "HTLC with HASH160 in conditions (must use PREIMAGE)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "HTLC", "fields": [
                {"type": "HASH160", "hex": "cc"*20},
                {"type": "NUMERIC", "hex": "90000000"},
                {"type": "SCHEME",  "hex": "01"},
                {"type": "PUBKEY",  "hex": "02" + "11"*32},
                {"type": "PUBKEY",  "hex": "02" + "22"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH160",
    },
    {
        "id": 18,
        "name": "ANCHOR_FEE with extra trailing NUMERIC (6 fields, expected 5)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR_FEE", "fields": [
                {"type": "SCHEME",  "hex": "01"},
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "NUMERIC", "hex": "64000000"},
                {"type": "NUMERIC", "hex": "a0860100"},
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "NUMERIC", "hex": "02000000"},  # extra
                {"type": "PUBKEY",  "hex": "02" + "11"*32},
                {"type": "PUBKEY",  "hex": "02" + "22"*32},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    # ─── Unknown block type string ───
    {
        "id": 19,
        "name": "Unknown block type string",
        "category": "unknown block type",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "NOT_A_REAL_BLOCK", "fields": []}],
        }],
        "expected_error_substring": "block type",
    },
    # ─── Invalid SCHEME byte ───
    {
        "id": 20,
        "name": "SIG with SCHEME = 0xFE (unknown scheme)",
        "category": "invalid SCHEME",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "SIG", "fields": [
                {"type": "SCHEME", "hex": "fe"},
                {"type": "PUBKEY", "hex": "02" + "11"*32},
            ]}],
        }],
        "expected_error_substring": "scheme",
    },
    # ─── Invalid pubkey length ───
    {
        "id": 21,
        "name": "SIG with 33-byte PUBKEY but invalid 0x04 prefix",
        "category": "invalid pubkey prefix",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "SIG", "fields": [
                {"type": "SCHEME", "hex": "01"},
                {"type": "PUBKEY", "hex": "04" + "11"*32},
            ]}],
        }],
        "expected_error_substring": "PUBKEY invalid prefix",
    },
    # ─── HASH160 in non-legacy block ───
    {
        "id": 22,
        "name": "HASH_SIG with raw HASH160 (must use PREIMAGE)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "HASH_SIG", "fields": [
                {"type": "HASH160", "hex": "cc"*20},
                {"type": "SCHEME",  "hex": "01"},
                {"type": "PUBKEY",  "hex": "02" + "11"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH160",
    },
    # ─── HYSTERESIS_FEE wrong field count ───
    {
        "id": 23,
        "name": "HYSTERESIS_FEE missing low rate (needs 2 NUMERIC)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "HYSTERESIS_FEE", "fields": [
                {"type": "NUMERIC", "hex": "64000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    # ─── OUTPUT_CHECK wrong shape ───
    {
        "id": 24,
        "name": "OUTPUT_CHECK with 3 NUMERICs (missing HASH256)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "OUTPUT_CHECK", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "NUMERIC", "hex": "10270000"},
                {"type": "NUMERIC", "hex": "00ca9a3b"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    # ─── RECURSE_SAME with HASH256 instead of NUMERIC ───
    {
        "id": 25,
        "name": "RECURSE_SAME with PREIMAGE (auto → HASH256, type mismatch)",
        "category": "field type mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "RECURSE_SAME", "fields": [
                {"type": "PREIMAGE", "hex": "ab"*32},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    # ─── Fixed-size violations (IsValid) ───
    {
        "id": 26,
        "name": "ACCUMULATOR with 31-byte HASH256 (must be 32)",
        "category": "fixed-size violation",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ACCUMULATOR", "fields": [
                {"type": "HASH256", "hex": "aa"*31},
            ]}],
        }],
        "expected_error_substring": "HASH256 too small",
    },
    {
        "id": 27,
        "name": "QABI_SPEND with 31-byte PUBKEY_COMMIT (must be 32)",
        "category": "fixed-size violation",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "QABI_SPEND", "fields": [
                {"type": "HASH256",       "hex": "aa"*32},
                {"type": "HASH256",       "hex": "00"*32},
                {"type": "NUMERIC",       "hex": "00000000"},
                {"type": "NUMERIC",       "hex": "01000000"},
                {"type": "PUBKEY_COMMIT", "hex": "ee"*31},
            ]}],
        }],
        "expected_error_substring": "PUBKEY_COMMIT too small",
    },
    {
        "id": 28,
        "name": "DATA_RETURN with 0-byte DATA (min 1)",
        "category": "size-bound violation",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "DATA_RETURN", "fields": [
                {"type": "DATA", "hex": ""},
            ]}],
        }],
        "expected_error_substring": "DATA too small",
    },
    {
        "id": 29,
        "name": "SIG with 2-byte SCHEME (must be 1)",
        "category": "fixed-size violation",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "SIG", "fields": [
                {"type": "SCHEME", "hex": "0102"},
                {"type": "PUBKEY", "hex": "02" + "11"*32},
            ]}],
        }],
        "expected_error_substring": "SCHEME too large",
    },
    {
        "id": 30,
        "name": "CTV with 31-byte HASH256 (must be 32)",
        "category": "fixed-size violation",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "CTV", "fields": [
                {"type": "HASH256", "hex": "cc"*31},
            ]}],
        }],
        "expected_error_substring": "HASH256 too small",
    },
    {
        "id": 31,
        "name": "ANCHOR with NUMERIC > 4 bytes (oversize)",
        "category": "oversize NUMERIC",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR", "fields": [
                {"type": "NUMERIC", "hex": "0102030405"},  # 5 bytes
            ]}],
        }],
        "expected_error_substring": "NUMERIC too large",
    },
    {
        "id": 32,
        "name": "TAGGED_HASH with HASH256 + 33-byte PREIMAGE (oversize)",
        "category": "oversize PREIMAGE",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "TAGGED_HASH", "fields": [
                {"type": "HASH256", "hex": "aa"*32},
                {"type": "PREIMAGE", "hex": "bb"*33},  # PREIMAGE max=32
            ]}],
        }],
        "expected_error_substring": "PREIMAGE too large",
    },
    {
        "id": 33,
        "name": "P2SH_LEGACY with 81-byte SCRIPT_BODY (max 80)",
        "category": "oversize SCRIPT_BODY",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "P2SH_LEGACY", "fields": [
                {"type": "SCRIPT_BODY", "hex": "ab" * 81},
            ]}],
        }],
        "expected_error_substring": "SCRIPT_BODY too large",
    },
    # ─── Witness-only data types in conditions ───
    {
        "id": 34,
        "name": "SIG with SIGNATURE in conditions (witness-only)",
        "category": "witness-only type in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "SIG", "fields": [
                {"type": "SCHEME",    "hex": "01"},
                {"type": "SIGNATURE", "hex": "33" * 64},
            ]}],
        }],
        "expected_error_substring": "not allowed in conditions",
    },
    {
        "id": 35,
        "name": "ANCHOR with MERKLE_PROOF (RPC unknown data type)",
        "category": "unknown data type at RPC layer",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR", "fields": [
                {"type": "MERKLE_PROOF", "hex": "44" * 64},
            ]}],
        }],
        "expected_error_substring": "Unknown data type",
    },
    # ─── More field-count and type errors per family ───
    {
        "id": 36,
        "name": "EPOCH_GATE with 1 NUMERIC (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "EPOCH_GATE", "fields": [
                {"type": "NUMERIC", "hex": "00000100"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 37,
        "name": "WEIGHT_LIMIT with 0 fields (needs 1)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "WEIGHT_LIMIT", "fields": []}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 38,
        "name": "INPUT_COUNT with PREIMAGE (auto → HASH256, expected NUMERIC)",
        "category": "field type mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "INPUT_COUNT", "fields": [
                {"type": "PREIMAGE", "hex": "ab"*16},
                {"type": "NUMERIC",  "hex": "0a000000"},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    {
        "id": 39,
        "name": "KEY_REF_SIG with 1 NUMERIC (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "KEY_REF_SIG", "fields": [
                {"type": "NUMERIC", "hex": "00000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 40,
        "name": "ANCHOR_RESERVE missing HASH256 (only 2 NUMERIC)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR_RESERVE", "fields": [
                {"type": "NUMERIC", "hex": "02000000"},
                {"type": "NUMERIC", "hex": "03000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 41,
        "name": "ANCHOR_POOL with NUMERIC at index 0 (expected HASH256)",
        "category": "field type mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR_POOL", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "NUMERIC", "hex": "07000000"},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    {
        "id": 42,
        "name": "ANCHOR_SEAL with 1 PREIMAGE only (needs 2 HASH256)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR_SEAL", "fields": [
                {"type": "PREIMAGE", "hex": "ab"*16},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 43,
        "name": "ONE_SHOT missing HASH256 (only NUMERIC)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ONE_SHOT", "fields": [
                {"type": "NUMERIC", "hex": "00000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 44,
        "name": "RATE_LIMIT with 2 NUMERICs (needs 3)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "RATE_LIMIT", "fields": [
                {"type": "NUMERIC", "hex": "0a000000"},
                {"type": "NUMERIC", "hex": "64000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 45,
        "name": "RECURSE_UNTIL with HASH256 (auto-fail: no auto-convert here)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "RECURSE_UNTIL", "fields": [
                {"type": "HASH256", "hex": "00"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH256",
    },
    {
        "id": 46,
        "name": "TIMELOCKED_MULTISIG with 3 header fields (needs 4)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "TIMELOCKED_MULTISIG", "fields": [
                {"type": "NUMERIC", "hex": "02000000"},
                {"type": "NUMERIC", "hex": "90000000"},
                {"type": "SCHEME",  "hex": "01"},
            ]}],
        }],
        "expected_error_substring": "requires at least one PUBKEY",
    },
    {
        "id": 47,
        "name": "ANCHOR_FEE with 5 NUMERICs and no SCHEME (auto-inserted → 6 fields, expected 5)",
        "category": "field count mismatch (after SCHEME auto-insert)",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR_FEE", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "NUMERIC", "hex": "64000000"},
                {"type": "NUMERIC", "hex": "a0860100"},
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "PUBKEY",  "hex": "02" + "11"*32},
                {"type": "PUBKEY",  "hex": "02" + "22"*32},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 48,
        "name": "P2TR_SCRIPT_LEGACY with raw HASH256 (must use SCRIPT_BODY)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "P2TR_SCRIPT_LEGACY", "fields": [
                {"type": "HASH256", "hex": "aa"*32},
                {"type": "PUBKEY",  "hex": "02" + "11"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH256",
    },
    {
        "id": 49,
        "name": "CTV with HASH160 (must be HASH256)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "CTV", "fields": [
                {"type": "HASH160", "hex": "cc"*20},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH160",
    },
    {
        "id": 50,
        "name": "COMPARE with PREIMAGE (auto → HASH256, expected NUMERIC)",
        "category": "field type mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "COMPARE", "fields": [
                {"type": "PREIMAGE", "hex": "ab"*16},
                {"type": "NUMERIC",  "hex": "01000000"},
                {"type": "NUMERIC",  "hex": "02000000"},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    {
        "id": 51,
        "name": "SEQUENCER with 1 NUMERIC (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "SEQUENCER", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 52,
        "name": "QABI_SPEND with 4 fields (needs 5)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "QABI_SPEND", "fields": [
                {"type": "HASH256", "hex": "aa"*32},
                {"type": "HASH256", "hex": "00"*32},
                {"type": "NUMERIC", "hex": "00000000"},
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 53,
        "name": "TAGGED_HASH with 1 HASH256 (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "TAGGED_HASH", "fields": [
                {"type": "HASH256", "hex": "aa"*32},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 54,
        "name": "OUTPUT_COUNT with 1 NUMERIC (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "OUTPUT_COUNT", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 55,
        "name": "RELATIVE_VALUE missing denominator (needs 2 NUMERIC)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "RELATIVE_VALUE", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    # ─── Iteration 9: structural gaps ─────────────────────────────────
    # Each block-family check has its own first-class rejection vector.
    {
        "id": 56,
        "name": "EPOCH_GATE with 1 NUMERIC (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "EPOCH_GATE", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 57,
        "name": "INPUT_COUNT with 1 NUMERIC (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "INPUT_COUNT", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 58,
        "name": "WEIGHT_LIMIT with 0 NUMERIC (needs 1)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "WEIGHT_LIMIT", "fields": []}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 59,
        "name": "RECURSE_SAME with raw HASH256 (must use PREIMAGE)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "RECURSE_SAME", "fields": [
                {"type": "HASH256", "hex": "aa"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH256",
    },
    {
        "id": 60,
        "name": "TIMER_OFF_DELAY with raw HASH160 (must use PREIMAGE)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "TIMER_OFF_DELAY", "fields": [
                {"type": "HASH160", "hex": "aa"*20},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH160",
    },
    {
        "id": 61,
        "name": "RECURSE_UNTIL with 2 NUMERIC (needs 1)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "RECURSE_UNTIL", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
                {"type": "NUMERIC", "hex": "02000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 62,
        "name": "ANCHOR with raw HASH256 (must use PREIMAGE)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR", "fields": [
                {"type": "HASH256", "hex": "cc"*32},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH256",
    },
    {
        "id": 64,
        "name": "HASH_GUARDED with HASH256 of wrong size (16 bytes)",
        "category": "fixed-size violation",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "HASH_GUARDED", "fields": [
                {"type": "HASH256", "hex": "ab"*16},  # 16 bytes, must be 32
            ]}],
        }],
        "expected_error_substring": "too small",
    },
    {
        "id": 65,
        "name": "TAGGED_HASH with HASH256 of wrong size (33 bytes)",
        "category": "fixed-size violation",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "TAGGED_HASH", "fields": [
                {"type": "HASH256", "hex": "cd"*33},  # 33 bytes
                {"type": "HASH256", "hex": "ef"*32},
            ]}],
        }],
        "expected_error_substring": "too large",
    },
    {
        "id": 66,
        "name": "CTV with NUMERIC (wrong field type)",
        "category": "field type mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "CTV", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    {
        "id": 67,
        "name": "AMOUNT_LOCK with three NUMERIC (over field count)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "AMOUNT_LOCK", "fields": [
                {"type": "NUMERIC", "hex": "10270000"},
                {"type": "NUMERIC", "hex": "00ca9a3b"},
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 68,
        "name": "RECURSE_SPLIT with 1 NUMERIC (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "RECURSE_SPLIT", "fields": [
                {"type": "NUMERIC", "hex": "04000000"},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 69,
        "name": "RECURSE_COUNT with raw HASH160 (must use PREIMAGE)",
        "category": "raw hash in conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "RECURSE_COUNT", "fields": [
                {"type": "HASH160", "hex": "aa"*20},
            ]}],
        }],
        "expected_error_substring": "Use PREIMAGE instead of HASH160",
    },
    {
        "id": 70,
        "name": "OUTPUT_COUNT with 0 NUMERIC (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "OUTPUT_COUNT", "fields": []}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    # 71 dropped: createrungtx silently pads/accepts truncated NUMERIC.
    # Documented as a separate audit observation (createrungtx is more
    # permissive than the consensus serialiser — fix would belong at the
    # createrungtx validation layer, not the vector catalog).
    {
        "id": 72,
        "name": "ANCHOR_SEAL with one HASH256 (needs 2)",
        "category": "field count mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR_SEAL", "fields": [
                {"type": "PREIMAGE", "hex": "ab"*16},
            ]}],
        }],
        "expected_error_substring": "field count mismatch",
    },
    {
        "id": 73,
        "name": "ANCHOR_POOL with NUMERIC and PREIMAGE swapped",
        "category": "field order mismatch",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "ANCHOR_POOL", "fields": [
                {"type": "NUMERIC",  "hex": "01000000"},
                {"type": "PREIMAGE", "hex": "ab"*16},
            ]}],
        }],
        "expected_error_substring": "type mismatch",
    },
    {
        "id": 74,
        "name": "MULTISIG with K=0 (rejected after F25)",
        "category": "MULTISIG K out of range",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "MULTISIG", "fields": [
                {"type": "NUMERIC", "hex": "00000000"},
                {"type": "SCHEME",  "hex": "01"},
                {"type": "PUBKEY", "hex": "02" + "11"*32},
                {"type": "PUBKEY", "hex": "02" + "22"*32},
            ]}],
        }],
        "expected_error_substring": "out of range",
    },
    {
        "id": 75,
        "name": "MULTISIG with K=3 over N=2 (rejected after F25)",
        "category": "MULTISIG K out of range",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "MULTISIG", "fields": [
                {"type": "NUMERIC", "hex": "03000000"},
                {"type": "SCHEME",  "hex": "01"},
                {"type": "PUBKEY", "hex": "02" + "11"*32},
                {"type": "PUBKEY", "hex": "02" + "22"*32},
            ]}],
        }],
        "expected_error_substring": "out of range",
    },
    # 76 dropped: createrungtx accepts only string block-type names; an
    # integer block-type value is rejected at the JSON deserialisation
    # layer with a generic schema error rather than a domain-specific
    # "unknown block type" message. Existing case 49 ("unknown block
    # type") already covers the consensus-level rejection.
    {
        "id": 77,
        "name": "DATA_RETURN with 0-byte payload",
        "category": "DATA_RETURN payload empty",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "DATA_RETURN", "fields": [
                {"type": "DATA", "hex": ""},
            ]}],
        }],
        "expected_error_substring": "DATA",
    },
    {
        "id": 78,
        "name": "QABI_PRIME with extraneous NUMERIC field (rejected after F26)",
        "category": "intentionally-empty conditions",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "QABI_PRIME", "fields": [
                {"type": "NUMERIC", "hex": "01000000"},
            ]}],
        }],
        "expected_error_substring": "no condition fields",
    },
    {
        "id": 79,
        "name": "VAULT_LOCK with 0-byte PUBKEY",
        "category": "fixed-size violation",
        "rungs": [{
            "output_index": 0,
            "blocks": [{"type": "VAULT_LOCK", "fields": [
                {"type": "PUBKEY",  "hex": ""},
                {"type": "PUBKEY",  "hex": "02" + "22"*32},
                {"type": "NUMERIC", "hex": "90000000"},
            ]}],
        }],
        "expected_error_substring": "too small",
    },
    # 80 dropped: createrungtx accepts a rung with zero blocks. The
    # consensus-level "every rung has at least one block" check fires at
    # spend/validate time, not at the createrungtx fund-time layer.
]


class GenerateRungTxNegVectors(BitcoinTestFramework):
    def set_test_params(self):
        self.num_nodes = 1
        self.setup_clean_chain = True
        self.noban_tx_relay = True

    def run_test(self):
        node = self.nodes[0]
        wallet = MiniWallet(node)
        self.generate(wallet, COINBASE_MATURITY + 5)

        vectors = []
        # createrungtx never broadcasts, so we can reuse one UTXO across
        # all rejection cases (mark_as_spent=False keeps it in the pool).
        utxo = wallet.get_utxo(mark_as_spent=False)
        amt = (Decimal(str(utxo["value"])) - Decimal("0.001")).quantize(Decimal("0.00000001"))
        for case in CASES:
            try:
                node.createrungtx(
                    [{"txid": utxo["txid"], "vout": utxo["vout"]}],
                    [amt],
                    case["rungs"],
                )
            except Exception as e:
                err = str(e)
                expected = case["expected_error_substring"]
                if expected.lower() not in err.lower():
                    raise AssertionError(
                        f"Case {case['id']} ({case['name']}): "
                        f"expected substring {expected!r} not in error {err!r}"
                    )
                vectors.append({
                    "id": case["id"],
                    "name": case["name"],
                    "category": case["category"],
                    "input_rungs": case["rungs"],
                    "expected_error_substring": expected,
                    "actual_error_message": err,
                })
                self.log.info(f"  case {case['id']:>2}: ok — {case['name']}")
                continue
            raise AssertionError(
                f"Case {case['id']} ({case['name']}): "
                f"expected createrungtx to fail but it succeeded"
            )

        write_vectors(
            vectors,
            "Reproducible v4 RUNG_TX rejection vectors. Each entry is "
            "a malformed createrungtx input plus the JSON-RPC error "
            "the node returned. Independent implementations must "
            "reject the input and surface a comparable error category. "
            "Generated by test/functional/generate_rung_tx_neg_vectors.py "
            "— re-run to regenerate.",
        )

        self.log.info(f"Generated {len(vectors)} negative vectors → {OUTPUT_PATH}")


if __name__ == "__main__":
    GenerateRungTxNegVectors(__file__).main()
