#!/usr/bin/env python3
# Copyright (c) 2026 The Bitcoin Core developers
# Copyright (c) 2026 defenwycke
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit/.
"""Generate src/test/data/rung_tx_vectors.json — reproducible v4 RUNG_TX
fund+spend reference vectors covering all eight witness-rule families
(Fixed N, Empty, Reveal P, Triplets K, Accumulator, Bridging,
PQ-anchor, Unspendable).

Run:
    python3 test/functional/generate_rung_tx_vectors.py

Each vector is generated by funding an MLSC output via createrungtx
(MiniWallet supplies the input + signs the bootstrap), then spending
the MLSC output via signrungtx where applicable. Key material is
derived deterministically from a seed string (SHA-256(seed)) so re-runs
produce byte-identical vectors.

This is the activation-gate-component-3 generator. The current set is
the seed for expansion toward the 50+ vector bar (positive + negative
+ edge cases per rule family).

The script writes to a temp file then renames over
src/test/data/rung_tx_vectors.json so partially-generated runs can't
corrupt the committed fixture.
"""

import hashlib
import json
import os
import sys
from decimal import Decimal
from pathlib import Path

from test_framework.blocktools import COINBASE_MATURITY
from test_framework.key import ECKey
from test_framework.messages import tx_from_hex
from test_framework.test_framework import BitcoinTestFramework, SkipTest
from test_framework.wallet import MiniWallet
from test_framework.wallet_util import bytes_to_wif


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "src" / "test" / "data" / "rung_tx_vectors.json"


def derive_key(seed: str) -> ECKey:
    """Deterministic ECKey from seed string. SHA-256 the seed; tweak the
    last byte if (extremely unlikely) it lands on the curve order or
    zero."""
    h = hashlib.sha256(seed.encode()).digest()
    if h == b"\x00" * 32:
        h = b"\x01" * 32
    k = ECKey()
    k.set(h, True)
    return k


def schnorr_pk_compressed(k: ECKey) -> bytes:
    return k.get_pubkey().get_bytes()


def write_vectors(vectors: list, source_description: str):
    payload = {
        "version": 1,
        "description": source_description,
        "vectors": vectors,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUTPUT_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(payload, indent=2) + "\n")
    tmp.replace(OUTPUT_PATH)
    print(f"wrote {len(vectors)} vectors → {OUTPUT_PATH}", file=sys.stderr)


# ──────────────────────────────────────────────────────────────────
# Vector helpers
# ──────────────────────────────────────────────────────────────────

def _fund_and_capture(node, wallet, rungs: list, label: str):
    """Drive a baseline fund tx via createrungtx + wallet sign;
    return the {fund_tx, mlsc_value_btc, conditions_root, spk}
    bundle."""
    utxo = wallet.get_utxo()
    amt = (Decimal(str(utxo["value"])) - Decimal("0.001")).quantize(Decimal("0.00000001"))
    result = node.createrungtx(
        [{"txid": utxo["txid"], "vout": utxo["vout"]}],
        [amt],
        rungs,
    )
    tx = tx_from_hex(result["hex"])
    wallet.sign_tx(tx)
    signed_hex = tx.serialize().hex()
    txid = node.sendrawtransaction(signed_hex)
    return {
        "fund_txid": txid,
        "fund_hex": signed_hex,
        "fund_size_bytes": len(signed_hex) // 2,
        "mlsc_scriptpubkey": result["scriptPubKey"],
        "mlsc_value_btc": float(amt),
        "conditions_root": result["conditions_root"],
        "key_path": result.get("key_path", False),
        "internal_pubkey": result.get("internal_pubkey"),
    }


# ──────────────────────────────────────────────────────────────────
# Vector specs — each function returns a vector dict
# ──────────────────────────────────────────────────────────────────
#
# Existing baseline (already in the fixture; re-generated here so the
# whole file is reproducible from this script):
#   1. SIG (Fixed N + key-path tweak)
#   2. P2WPKH_LEGACY (Bridging — HASH160-committed pubkey)
#   3. HTLC (Reveal P + Triplets K — claim path)
#
# New positive coverage:
#   4. CSV (Empty — relative timelock)
#   5. CLTV (Empty — absolute timelock)
#   6. MULTISIG 2-of-3 (Triplets K — proper multisig with inner-Merkle)
#   7. CTV (Empty — covenant template hash)
#   8. PQ_BATCH single-input (PQ-anchor — anchor witness only)
#   9. DATA_RETURN (Unspendable — embed payload, never spend)
#
# Future expansion: ACCUMULATOR (Accumulator), HASH_GUARDED (Reveal-P),
# P2SH_LEGACY (Bridging with inner CSV), VAULT_LOCK (Fixed N w/ 2 keys),
# TIMELOCKED_MULTISIG, ANCHOR_FEE, plus negative vectors for each
# rule family.


def vec_1_sig_keypath(node, wallet) -> dict:
    seed_fund = "bip-xxxx-vec1-fund-key"
    seed_sweep = "bip-xxxx-vec1-sweep-key"
    fund_pk = derive_key(seed_fund)
    sweep_pk = derive_key(seed_sweep)
    fund_pk_hex = schnorr_pk_compressed(fund_pk).hex()
    sweep_pk_hex = schnorr_pk_compressed(sweep_pk).hex()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "SIG", "fields": [
            {"type": "SCHEME", "hex": "01"},
            {"type": "PUBKEY", "hex": fund_pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec1")
    return {
        "id": 1,
        "name": "SIG single-rung Schnorr key-path",
        "witness_rule": "Fixed N + key-path tweak",
        "block_types": ["SIG"],
        "key_seeds": {"fund": seed_fund, "sweep": seed_sweep},
        "fund_pubkey_compressed": fund_pk_hex,
        "sweep_pubkey_compressed": sweep_pk_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_2_p2wpkh_legacy(node, wallet) -> dict:
    seed_p2wpkh = "bip-xxxx-vec2-p2wpkh-key"
    pk = derive_key(seed_p2wpkh)
    pk_hex = schnorr_pk_compressed(pk).hex()
    # P2WPKH_LEGACY conditions take PUBKEY in the spec; createrungtx
    # computes HASH160 itself.
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "P2WPKH_LEGACY", "fields": [
            {"type": "PUBKEY", "hex": pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec2")
    return {
        "id": 2,
        "name": "P2WPKH_LEGACY wrapper (HASH160-committed pubkey)",
        "witness_rule": "Bridging (legacy P2*)",
        "block_types": ["P2WPKH_LEGACY"],
        "key_seeds": {"p2wpkh": seed_p2wpkh},
        "p2wpkh_pubkey_compressed": pk_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_3_htlc(node, wallet) -> dict:
    seed_recv = "bip-xxxx-vec3-htlc-recv"
    seed_send = "bip-xxxx-vec3-htlc-send"
    recv_pk = derive_key(seed_recv)
    send_pk = derive_key(seed_send)
    recv_pk_hex = schnorr_pk_compressed(recv_pk).hex()
    send_pk_hex = schnorr_pk_compressed(send_pk).hex()
    preimage = b"\x42" * 32
    payment_hash = hashlib.sha256(preimage).digest()
    # HTLC conditions: [HASH256, NUMERIC(csv), SCHEME] — createrungtx
    # accepts HASH256 directly here (it's an external commitment, not
    # auto-derived from PREIMAGE for HTLC's claim path).
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "HTLC", "fields": [
            {"type": "PREIMAGE", "hex": preimage.hex()},  # createrungtx will compute HASH256
            {"type": "NUMERIC",  "hex": "90000000"},     # CSV = 144 (LE)
            {"type": "SCHEME",   "hex": "01"},
            {"type": "PUBKEY",   "hex": recv_pk_hex},
            {"type": "PUBKEY",   "hex": send_pk_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec3")
    return {
        "id": 3,
        "name": "HTLC (claim path: preimage + sig)",
        "witness_rule": "Fixed 5 (Triplets K + Reveal P)",
        "block_types": ["HTLC"],
        "key_seeds": {"recv": seed_recv, "send": seed_send},
        "recv_pubkey_compressed": recv_pk_hex,
        "send_pubkey_compressed": send_pk_hex,
        "preimage_hex": preimage.hex(),
        "payment_hash_hex": payment_hash.hex(),
        "csv_blocks": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_4_csv(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CSV", "fields": [
            {"type": "NUMERIC", "hex": "90000000"},  # 144 blocks LE
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec4")
    return {
        "id": 4,
        "name": "CSV relative-timelock (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["CSV"],
        "csv_blocks": 144,
        "fund_tx": _shape_fund(fb),
    }


def vec_5_cltv(node, wallet) -> dict:
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CLTV", "fields": [
            {"type": "NUMERIC", "hex": "00000000"},  # 0 = no actual time-lock
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec5")
    return {
        "id": 5,
        "name": "CLTV absolute-timelock (Empty witness rule)",
        "witness_rule": "Empty",
        "block_types": ["CLTV"],
        "cltv_height": 0,
        "fund_tx": _shape_fund(fb),
    }


def vec_6_multisig_2of3(node, wallet) -> dict:
    seeds = ["bip-xxxx-vec6-msig-a", "bip-xxxx-vec6-msig-b", "bip-xxxx-vec6-msig-c"]
    pks = [derive_key(s) for s in seeds]
    pk_hexes = [schnorr_pk_compressed(k).hex() for k in pks]
    # createrungtx for MULTISIG takes the full pubkey list and computes
    # the inner-Merkle pubkey root commit itself (post-E-018a).
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "MULTISIG", "fields": [
            {"type": "NUMERIC", "hex": "02000000"},   # K = 2
            {"type": "SCHEME",  "hex": "01"},          # SCHNORR
            {"type": "PUBKEY",  "hex": pk_hexes[0]},   # canonical sort
            {"type": "PUBKEY",  "hex": pk_hexes[1]},
            {"type": "PUBKEY",  "hex": pk_hexes[2]},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec6")
    return {
        "id": 6,
        "name": "MULTISIG 2-of-3 with inner-Merkle pubkey commit",
        "witness_rule": "Triplets K",
        "block_types": ["MULTISIG"],
        "key_seeds": {f"k{i}": s for i, s in enumerate(seeds)},
        "pubkeys_compressed": pk_hexes,
        "threshold": 2,
        "fund_tx": _shape_fund(fb),
    }


def vec_7_ctv(node, wallet) -> dict:
    # CTV's HASH256 is a template hash; we use a placeholder here
    # because the test fixture documents the wire shape, not a working
    # spend. (A working CTV spend would derive the hash via
    # computectvhash from a fully-specified spending tx template.)
    template_hash = b"\xcc" * 32
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "CTV", "fields": [
            {"type": "HASH256", "hex": template_hash.hex()},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec7")
    return {
        "id": 7,
        "name": "CTV BIP-119 covenant (Empty witness rule)",
        "witness_rule": "Empty (post-E-023)",
        "block_types": ["CTV"],
        "template_hash_hex": template_hash.hex(),
        "fund_tx": _shape_fund(fb),
    }


def vec_8_pq_batch_anchor(node, wallet) -> dict:
    # Probe liboqs availability.
    try:
        kp = node.generatepqkeypair("FALCON512")
    except Exception as e:
        if "liboqs" in str(e).lower():
            return None  # skip — not a hard requirement for the fixture
        raise
    pubkey_hex = kp["pubkey"]
    commit_hex = hashlib.sha256(bytes.fromhex(pubkey_hex)).hexdigest()
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "PQ_BATCH", "fields": [
            {"type": "HASH256", "hex": commit_hex},
        ]}],
    }]
    fb = _fund_and_capture(node, wallet, rungs, "vec8")
    return {
        "id": 8,
        "name": "PQ_BATCH single-anchor input (FALCON-512)",
        "witness_rule": "PQ-anchor",
        "block_types": ["PQ_BATCH"],
        "falcon_pubkey_size_bytes": len(pubkey_hex) // 2,
        "commit_sha256_hex": commit_hex,
        "fund_tx": _shape_fund(fb),
    }


def vec_9_data_return(node, wallet) -> dict:
    # DATA_RETURN: 8-byte nValue == 0 + payload up to 40 bytes on the
    # wire. createrungtx accepts the data field directly.
    payload = b"vec9-data-return-fixture-test"
    assert len(payload) <= 40
    rungs = [{
        "output_index": 0,
        "blocks": [{"type": "DATA_RETURN", "fields": [
            {"type": "DATA", "hex": payload.hex()},
        ]}],
    }]
    # DATA_RETURN funds with nValue = 0 — we need ONE non-DATA_RETURN
    # output (any v4 output) to satisfy the per-tx "every output has at
    # least one rung" check. Use a SIG rung at output_index=1 that
    # carries a single-block SIG with a placeholder pubkey.
    placeholder_pk = derive_key("bip-xxxx-vec9-placeholder").get_pubkey().get_bytes().hex()
    rungs.append({
        "output_index": 1,
        "blocks": [{"type": "SIG", "fields": [
            {"type": "SCHEME", "hex": "01"},
            {"type": "PUBKEY", "hex": placeholder_pk},
        ]}],
    })
    utxo = wallet.get_utxo()
    spendable_amt = (Decimal(str(utxo["value"])) - Decimal("0.002")).quantize(Decimal("0.00000001"))
    result = node.createrungtx(
        [{"txid": utxo["txid"], "vout": utxo["vout"]}],
        [Decimal("0.00000000"), spendable_amt],
        rungs,
    )
    tx = tx_from_hex(result["hex"])
    wallet.sign_tx(tx)
    signed_hex = tx.serialize().hex()
    txid = node.sendrawtransaction(signed_hex)
    return {
        "id": 9,
        "name": "DATA_RETURN payload + SIG vout (Unspendable witness rule)",
        "witness_rule": "Unspendable",
        "block_types": ["DATA_RETURN", "SIG"],
        "data_return_payload_hex": payload.hex(),
        "data_return_payload_len": len(payload),
        "fund_tx": {
            "txid": txid,
            "hex": signed_hex,
            "size_bytes": len(signed_hex) // 2,
            "mlsc_scriptpubkey": result["scriptPubKey"],
            "conditions_root": result["conditions_root"],
            "vouts": 2,
        },
    }


def _shape_fund(fb: dict) -> dict:
    """Convert _fund_and_capture's bundle to the spec's fund_tx schema."""
    out = {
        "txid": fb["fund_txid"],
        "hex": fb["fund_hex"],
        "size_bytes": fb["fund_size_bytes"],
        "mlsc_scriptpubkey": fb["mlsc_scriptpubkey"],
        "mlsc_value_btc": fb["mlsc_value_btc"],
        "conditions_root": fb["conditions_root"],
        "key_path": fb["key_path"],
    }
    if fb.get("internal_pubkey"):
        out["internal_pubkey"] = fb["internal_pubkey"]
    return out


# ──────────────────────────────────────────────────────────────────
# Generator entry
# ──────────────────────────────────────────────────────────────────

class GenerateRungTxVectors(BitcoinTestFramework):
    def set_test_params(self):
        self.num_nodes = 1
        self.setup_clean_chain = True
        self.noban_tx_relay = True

    def run_test(self):
        node = self.nodes[0]
        wallet = MiniWallet(node)
        self.generate(wallet, COINBASE_MATURITY + 20)

        builders = [
            vec_1_sig_keypath,
            vec_2_p2wpkh_legacy,
            vec_3_htlc,
            vec_4_csv,
            vec_5_cltv,
            vec_6_multisig_2of3,
            vec_7_ctv,
            vec_8_pq_batch_anchor,
            vec_9_data_return,
        ]
        vectors = []
        for builder in builders:
            try:
                v = builder(node, wallet)
                if v is None:
                    self.log.info(f"  {builder.__name__}: skipped")
                    continue
                vectors.append(v)
                self.generate(node, 1)
                self.log.info(f"  {builder.__name__}: ok (id {v['id']})")
            except Exception as e:
                self.log.error(f"  {builder.__name__}: FAILED — {e}")
                raise

        write_vectors(
            vectors,
            "Reproducible v4 RUNG_TX fund (and where applicable spend) "
            "transaction vectors. Generated by "
            "test/functional/generate_rung_tx_vectors.py — re-run to "
            "regenerate. Covers the eight witness-rule families: "
            "Fixed N (vec 1), Bridging (vec 2), Reveal P + Triplets K "
            "(vec 3), Empty (vec 4, 5, 7), Triplets K (vec 6), "
            "PQ-anchor (vec 8), Unspendable (vec 9). Negative vectors "
            "and remaining rules (Accumulator, more Bridging variants) "
            "tracked in test/functional/feature_rung_anti_embedding.py "
            "and to be appended in subsequent passes toward the "
            "activation gate's 50+ vector bar.",
        )

        self.log.info(f"Generated {len(vectors)} vectors → {OUTPUT_PATH}")


if __name__ == "__main__":
    GenerateRungTxVectors(__file__).main()
